# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='NetworkAuth',
        ),
    ]
