/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigureSensorTaskR
 */
export interface ConfigureSensorTaskR {
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTaskR
     */
    created?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTaskR
     */
    started?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTaskR
     */
    firstDiscovery?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTaskR
     */
    lastDiscovery?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTaskR
     */
    finished?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ConfigureSensorTaskR
     */
    error?: string | null;
    /**
     * ID
     * @type {number}
     * @memberof ConfigureSensorTaskR
     */
    id: number;
}

/**
 * Check if a given object implements the ConfigureSensorTaskR interface.
 */
export function instanceOfConfigureSensorTaskR(value: object): value is ConfigureSensorTaskR {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ConfigureSensorTaskRFromJSON(json: any): ConfigureSensorTaskR {
    return ConfigureSensorTaskRFromJSONTyped(json, false);
}

export function ConfigureSensorTaskRFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureSensorTaskR {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
        'firstDiscovery': json['first_discovery'] == null ? undefined : (new Date(json['first_discovery'])),
        'lastDiscovery': json['last_discovery'] == null ? undefined : (new Date(json['last_discovery'])),
        'finished': json['finished'] == null ? undefined : (new Date(json['finished'])),
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'],
    };
}

export function ConfigureSensorTaskRToJSON(json: any): ConfigureSensorTaskR {
    return ConfigureSensorTaskRToJSONTyped(json, false);
}

export function ConfigureSensorTaskRToJSONTyped(value?: ConfigureSensorTaskR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'] == null ? value['created'] : value['created'].toISOString(),
        'started': value['started'] == null ? value['started'] : value['started'].toISOString(),
        'first_discovery': value['firstDiscovery'] == null ? value['firstDiscovery'] : value['firstDiscovery'].toISOString(),
        'last_discovery': value['lastDiscovery'] == null ? value['lastDiscovery'] : value['lastDiscovery'].toISOString(),
        'finished': value['finished'] == null ? value['finished'] : value['finished'].toISOString(),
        'error': value['error'],
        'id': value['id'],
    };
}

