/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigureSensorTaskW
 */
export interface ConfigureSensorTaskW {
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ConfigureSensorTaskW
     */
    sensorId: number;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ConfigureSensorTaskW
     */
    sensorName?: string | null;
}

/**
 * Check if a given object implements the ConfigureSensorTaskW interface.
 */
export function instanceOfConfigureSensorTaskW(value: object): value is ConfigureSensorTaskW {
    if (!('sensorId' in value) || value['sensorId'] === undefined) return false;
    return true;
}

export function ConfigureSensorTaskWFromJSON(json: any): ConfigureSensorTaskW {
    return ConfigureSensorTaskWFromJSONTyped(json, false);
}

export function ConfigureSensorTaskWFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureSensorTaskW {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorId': json['sensor_id'],
        'sensorName': json['sensor_name'] == null ? undefined : json['sensor_name'],
    };
}

export function ConfigureSensorTaskWToJSON(json: any): ConfigureSensorTaskW {
    return ConfigureSensorTaskWToJSONTyped(json, false);
}

export function ConfigureSensorTaskWToJSONTyped(value?: ConfigureSensorTaskW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensor_id': value['sensorId'],
        'sensor_name': value['sensorName'],
    };
}

