/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigureSensorTask
 */
export interface ConfigureSensorTask {
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTask
     */
    created?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTask
     */
    started?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTask
     */
    firstDiscovery?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTask
     */
    lastDiscovery?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof ConfigureSensorTask
     */
    finished?: Date | null;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ConfigureSensorTask
     */
    error?: string | null;
    /**
     * ID
     * @type {number}
     * @memberof ConfigureSensorTask
     */
    id: number;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ConfigureSensorTask
     */
    sensorId: number;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ConfigureSensorTask
     */
    sensorName: string;
}

/**
 * Check if a given object implements the ConfigureSensorTask interface.
 */
export function instanceOfConfigureSensorTask(value: object): value is ConfigureSensorTask {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sensorId' in value) || value['sensorId'] === undefined) return false;
    if (!('sensorName' in value) || value['sensorName'] === undefined) return false;
    return true;
}

export function ConfigureSensorTaskFromJSON(json: any): ConfigureSensorTask {
    return ConfigureSensorTaskFromJSONTyped(json, false);
}

export function ConfigureSensorTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureSensorTask {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
        'firstDiscovery': json['first_discovery'] == null ? undefined : (new Date(json['first_discovery'])),
        'lastDiscovery': json['last_discovery'] == null ? undefined : (new Date(json['last_discovery'])),
        'finished': json['finished'] == null ? undefined : (new Date(json['finished'])),
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'],
        'sensorId': json['sensor_id'],
        'sensorName': json['sensor_name'],
    };
}

export function ConfigureSensorTaskToJSON(json: any): ConfigureSensorTask {
    return ConfigureSensorTaskToJSONTyped(json, false);
}

export function ConfigureSensorTaskToJSONTyped(value?: ConfigureSensorTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'] == null ? value['created'] : value['created'].toISOString(),
        'started': value['started'] == null ? value['started'] : value['started'].toISOString(),
        'first_discovery': value['firstDiscovery'] == null ? value['firstDiscovery'] : value['firstDiscovery'].toISOString(),
        'last_discovery': value['lastDiscovery'] == null ? value['lastDiscovery'] : value['lastDiscovery'].toISOString(),
        'finished': value['finished'] == null ? value['finished'] : value['finished'].toISOString(),
        'error': value['error'],
        'id': value['id'],
        'sensor_id': value['sensorId'],
        'sensor_name': value['sensorName'],
    };
}

