/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControlR
 */
export interface ControlR {
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ControlR
     */
    sensorId: number;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ControlR
     */
    name: string;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ControlR
     */
    temperature?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ControlR
     */
    targetTemp?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ControlR
     */
    pidcontrol?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof ControlR
     */
    age?: number | null;
    /**
     * ID
     * @type {number}
     * @memberof ControlR
     */
    id: number;
}

/**
 * Check if a given object implements the ControlR interface.
 */
export function instanceOfControlR(value: object): value is ControlR {
    if (!('sensorId' in value) || value['sensorId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ControlRFromJSON(json: any): ControlR {
    return ControlRFromJSONTyped(json, false);
}

export function ControlRFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlR {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorId': json['sensor_id'],
        'name': json['name'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
        'pidcontrol': json['pidcontrol'] == null ? undefined : json['pidcontrol'],
        'age': json['age'] == null ? undefined : json['age'],
        'id': json['id'],
    };
}

export function ControlRToJSON(json: any): ControlR {
    return ControlRToJSONTyped(json, false);
}

export function ControlRToJSONTyped(value?: ControlR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensor_id': value['sensorId'],
        'name': value['name'],
        'temperature': value['temperature'],
        'target_temp': value['targetTemp'],
        'pidcontrol': value['pidcontrol'],
        'age': value['age'],
        'id': value['id'],
    };
}

