/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Control
 */
export interface Control {
    /**
     * resource uri
     * @type {string}
     * @memberof Control
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Control
     */
    sensorId: number;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof Control
     */
    name: string;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Control
     */
    temperature?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Control
     */
    targetTemp?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Control
     */
    pidcontrol?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Control
     */
    age?: number | null;
    /**
     * ID
     * @type {number}
     * @memberof Control
     */
    id: number;
    /**
     * kp
     * @type {number}
     * @memberof Control
     */
    kp: number;
    /**
     * ki
     * @type {number}
     * @memberof Control
     */
    ki: number;
    /**
     * kd
     * @type {number}
     * @memberof Control
     */
    kd: number;
    /**
     * intabsmax
     * @type {number}
     * @memberof Control
     */
    intabsmax?: number | null;
}

/**
 * Check if a given object implements the Control interface.
 */
export function instanceOfControl(value: object): value is Control {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('sensorId' in value) || value['sensorId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kp' in value) || value['kp'] === undefined) return false;
    if (!('ki' in value) || value['ki'] === undefined) return false;
    if (!('kd' in value) || value['kd'] === undefined) return false;
    return true;
}

export function ControlFromJSON(json: any): Control {
    return ControlFromJSONTyped(json, false);
}

export function ControlFromJSONTyped(json: any, ignoreDiscriminator: boolean): Control {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'sensorId': json['sensor_id'],
        'name': json['name'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
        'pidcontrol': json['pidcontrol'] == null ? undefined : json['pidcontrol'],
        'age': json['age'] == null ? undefined : json['age'],
        'id': json['id'],
        'kp': json['kp'],
        'ki': json['ki'],
        'kd': json['kd'],
        'intabsmax': json['intabsmax'] == null ? undefined : json['intabsmax'],
    };
}

export function ControlToJSON(json: any): Control {
    return ControlToJSONTyped(json, false);
}

export function ControlToJSONTyped(value?: Control | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'sensor_id': value['sensorId'],
        'name': value['name'],
        'temperature': value['temperature'],
        'target_temp': value['targetTemp'],
        'pidcontrol': value['pidcontrol'],
        'age': value['age'],
        'id': value['id'],
        'kp': value['kp'],
        'ki': value['ki'],
        'kd': value['kd'],
        'intabsmax': value['intabsmax'],
    };
}

