/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControlW
 */
export interface ControlW {
    /**
     * kp
     * @type {number}
     * @memberof ControlW
     */
    kp: number;
    /**
     * ki
     * @type {number}
     * @memberof ControlW
     */
    ki: number;
    /**
     * kd
     * @type {number}
     * @memberof ControlW
     */
    kd: number;
    /**
     * intabsmax
     * @type {number}
     * @memberof ControlW
     */
    intabsmax?: number | null;
}

/**
 * Check if a given object implements the ControlW interface.
 */
export function instanceOfControlW(value: object): value is ControlW {
    if (!('kp' in value) || value['kp'] === undefined) return false;
    if (!('ki' in value) || value['ki'] === undefined) return false;
    if (!('kd' in value) || value['kd'] === undefined) return false;
    return true;
}

export function ControlWFromJSON(json: any): ControlW {
    return ControlWFromJSONTyped(json, false);
}

export function ControlWFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlW {
    if (json == null) {
        return json;
    }
    return {
        
        'kp': json['kp'],
        'ki': json['ki'],
        'kd': json['kd'],
        'intabsmax': json['intabsmax'] == null ? undefined : json['intabsmax'],
    };
}

export function ControlWToJSON(json: any): ControlW {
    return ControlWToJSONTyped(json, false);
}

export function ControlWToJSONTyped(value?: ControlW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kp': value['kp'],
        'ki': value['ki'],
        'kd': value['kd'],
        'intabsmax': value['intabsmax'],
    };
}

