/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentDaytype
 */
export interface CurrentDaytype {
    /**
     * resource uri
     * @type {string}
     * @memberof CurrentDaytype
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof CurrentDaytype
     */
    daytype: string;
}

/**
 * Check if a given object implements the CurrentDaytype interface.
 */
export function instanceOfCurrentDaytype(value: object): value is CurrentDaytype {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('daytype' in value) || value['daytype'] === undefined) return false;
    return true;
}

export function CurrentDaytypeFromJSON(json: any): CurrentDaytype {
    return CurrentDaytypeFromJSONTyped(json, false);
}

export function CurrentDaytypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentDaytype {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'daytype': json['daytype'],
    };
}

export function CurrentDaytypeToJSON(json: any): CurrentDaytype {
    return CurrentDaytypeToJSONTyped(json, false);
}

export function CurrentDaytypeToJSONTyped(value?: CurrentDaytype | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'daytype': value['daytype'],
    };
}

