/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentDaytypeR
 */
export interface CurrentDaytypeR {
    /**
     * resource uri
     * @type {string}
     * @memberof CurrentDaytypeR
     */
    resourceUri: string;
}

/**
 * Check if a given object implements the CurrentDaytypeR interface.
 */
export function instanceOfCurrentDaytypeR(value: object): value is CurrentDaytypeR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    return true;
}

export function CurrentDaytypeRFromJSON(json: any): CurrentDaytypeR {
    return CurrentDaytypeRFromJSONTyped(json, false);
}

export function CurrentDaytypeRFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentDaytypeR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
    };
}

export function CurrentDaytypeRToJSON(json: any): CurrentDaytypeR {
    return CurrentDaytypeRToJSONTyped(json, false);
}

export function CurrentDaytypeRToJSONTyped(value?: CurrentDaytypeR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
    };
}

