/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentDaytypeW
 */
export interface CurrentDaytypeW {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof CurrentDaytypeW
     */
    daytype: string;
}

/**
 * Check if a given object implements the CurrentDaytypeW interface.
 */
export function instanceOfCurrentDaytypeW(value: object): value is CurrentDaytypeW {
    if (!('daytype' in value) || value['daytype'] === undefined) return false;
    return true;
}

export function CurrentDaytypeWFromJSON(json: any): CurrentDaytypeW {
    return CurrentDaytypeWFromJSONTyped(json, false);
}

export function CurrentDaytypeWFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentDaytypeW {
    if (json == null) {
        return json;
    }
    return {
        
        'daytype': json['daytype'],
    };
}

export function CurrentDaytypeWToJSON(json: any): CurrentDaytypeW {
    return CurrentDaytypeWToJSONTyped(json, false);
}

export function CurrentDaytypeWToJSONTyped(value?: CurrentDaytypeW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'daytype': value['daytype'],
    };
}

