/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayType
 */
export interface DayType {
    /**
     * ID
     * @type {number}
     * @memberof DayType
     */
    id: number;
    /**
     * name
     * @type {string}
     * @memberof DayType
     */
    name: string;
}

/**
 * Check if a given object implements the DayType interface.
 */
export function instanceOfDayType(value: object): value is DayType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DayTypeFromJSON(json: any): DayType {
    return DayTypeFromJSONTyped(json, false);
}

export function DayTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function DayTypeToJSON(json: any): DayType {
    return DayTypeToJSONTyped(json, false);
}

export function DayTypeToJSONTyped(value?: DayType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

