/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayTypeW
 */
export interface DayTypeW {
    /**
     * name
     * @type {string}
     * @memberof DayTypeW
     */
    name: string;
}

/**
 * Check if a given object implements the DayTypeW interface.
 */
export function instanceOfDayTypeW(value: object): value is DayTypeW {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DayTypeWFromJSON(json: any): DayTypeW {
    return DayTypeWFromJSONTyped(json, false);
}

export function DayTypeWFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayTypeW {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function DayTypeWToJSON(json: any): DayTypeW {
    return DayTypeWToJSONTyped(json, false);
}

export function DayTypeWToJSONTyped(value?: DayTypeW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

