/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayTypeR
 */
export interface DayTypeR {
    /**
     * resource uri
     * @type {string}
     * @memberof DayTypeR
     */
    resourceUri: string;
    /**
     * ID
     * @type {number}
     * @memberof DayTypeR
     */
    id: number;
}

/**
 * Check if a given object implements the DayTypeR interface.
 */
export function instanceOfDayTypeR(value: object): value is DayTypeR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DayTypeRFromJSON(json: any): DayTypeR {
    return DayTypeRFromJSONTyped(json, false);
}

export function DayTypeRFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayTypeR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
    };
}

export function DayTypeRToJSON(json: any): DayTypeR {
    return DayTypeRToJSONTyped(json, false);
}

export function DayTypeRToJSONTyped(value?: DayTypeR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
    };
}

