/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantProfile
 */
export interface InstantProfile {
    /**
     * ID
     * @type {number}
     * @memberof InstantProfile
     */
    id: number;
    /**
     * name
     * @type {string}
     * @memberof InstantProfile
     */
    name: string;
    /**
     * active
     * @type {boolean}
     * @memberof InstantProfile
     */
    active: boolean;
}

/**
 * Check if a given object implements the InstantProfile interface.
 */
export function instanceOfInstantProfile(value: object): value is InstantProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function InstantProfileFromJSON(json: any): InstantProfile {
    return InstantProfileFromJSONTyped(json, false);
}

export function InstantProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'active': json['active'],
    };
}

export function InstantProfileToJSON(json: any): InstantProfile {
    return InstantProfileToJSONTyped(json, false);
}

export function InstantProfileToJSONTyped(value?: InstantProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'active': value['active'],
    };
}

