/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantProfileW
 */
export interface InstantProfileW {
    /**
     * ID
     * @type {number}
     * @memberof InstantProfileW
     */
    id: number;
    /**
     * name
     * @type {string}
     * @memberof InstantProfileW
     */
    name: string;
    /**
     * active
     * @type {boolean}
     * @memberof InstantProfileW
     */
    active: boolean;
}

/**
 * Check if a given object implements the InstantProfileW interface.
 */
export function instanceOfInstantProfileW(value: object): value is InstantProfileW {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function InstantProfileWFromJSON(json: any): InstantProfileW {
    return InstantProfileWFromJSONTyped(json, false);
}

export function InstantProfileWFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantProfileW {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'active': json['active'],
    };
}

export function InstantProfileWToJSON(json: any): InstantProfileW {
    return InstantProfileWToJSONTyped(json, false);
}

export function InstantProfileWToJSONTyped(value?: InstantProfileW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'active': value['active'],
    };
}

