/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantProfileR
 */
export interface InstantProfileR {
    /**
     * ID
     * @type {number}
     * @memberof InstantProfileR
     */
    id: number;
}

/**
 * Check if a given object implements the InstantProfileR interface.
 */
export function instanceOfInstantProfileR(value: object): value is InstantProfileR {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function InstantProfileRFromJSON(json: any): InstantProfileR {
    return InstantProfileRFromJSONTyped(json, false);
}

export function InstantProfileRFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantProfileR {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function InstantProfileRToJSON(json: any): InstantProfileR {
    return InstantProfileRToJSONTyped(json, false);
}

export function InstantProfileRToJSONTyped(value?: InstantProfileR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

