/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantOverrideR
 */
export interface InstantOverrideR {
    /**
     * resource uri
     * @type {string}
     * @memberof InstantOverrideR
     */
    resourceUri: string;
}

/**
 * Check if a given object implements the InstantOverrideR interface.
 */
export function instanceOfInstantOverrideR(value: object): value is InstantOverrideR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    return true;
}

export function InstantOverrideRFromJSON(json: any): InstantOverrideR {
    return InstantOverrideRFromJSONTyped(json, false);
}

export function InstantOverrideRFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantOverrideR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
    };
}

export function InstantOverrideRToJSON(json: any): InstantOverrideR {
    return InstantOverrideRToJSONTyped(json, false);
}

export function InstantOverrideRToJSONTyped(value?: InstantOverrideR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
    };
}

