/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantOverride
 */
export interface InstantOverride {
    /**
     * resource uri
     * @type {string}
     * @memberof InstantOverride
     */
    resourceUri: string;
    /**
     * resource uri
     * @type {string}
     * @memberof InstantOverride
     */
    control: string;
    /**
     * target temp
     * @type {number}
     * @memberof InstantOverride
     */
    targetTemp: number;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof InstantOverride
     */
    duration: number;
}

/**
 * Check if a given object implements the InstantOverride interface.
 */
export function instanceOfInstantOverride(value: object): value is InstantOverride {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('targetTemp' in value) || value['targetTemp'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    return true;
}

export function InstantOverrideFromJSON(json: any): InstantOverride {
    return InstantOverrideFromJSONTyped(json, false);
}

export function InstantOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'control': json['control'],
        'targetTemp': json['target_temp'],
        'duration': json['duration'],
    };
}

export function InstantOverrideToJSON(json: any): InstantOverride {
    return InstantOverrideToJSONTyped(json, false);
}

export function InstantOverrideToJSONTyped(value?: InstantOverride | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'control': value['control'],
        'target_temp': value['targetTemp'],
        'duration': value['duration'],
    };
}

