/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstantOverrideW
 */
export interface InstantOverrideW {
    /**
     * resource uri
     * @type {string}
     * @memberof InstantOverrideW
     */
    control: string;
    /**
     * target temp
     * @type {number}
     * @memberof InstantOverrideW
     */
    targetTemp: number;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof InstantOverrideW
     */
    duration: number;
}

/**
 * Check if a given object implements the InstantOverrideW interface.
 */
export function instanceOfInstantOverrideW(value: object): value is InstantOverrideW {
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('targetTemp' in value) || value['targetTemp'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    return true;
}

export function InstantOverrideWFromJSON(json: any): InstantOverrideW {
    return InstantOverrideWFromJSONTyped(json, false);
}

export function InstantOverrideWFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantOverrideW {
    if (json == null) {
        return json;
    }
    return {
        
        'control': json['control'],
        'targetTemp': json['target_temp'],
        'duration': json['duration'],
    };
}

export function InstantOverrideWToJSON(json: any): InstantOverrideW {
    return InstantOverrideWToJSONTyped(json, false);
}

export function InstantOverrideWToJSONTyped(value?: InstantOverrideW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'control': value['control'],
        'target_temp': value['targetTemp'],
        'duration': value['duration'],
    };
}

