/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMeta
 */
export interface ListMeta {
    /**
     * 
     * @type {number}
     * @memberof ListMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ListMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the ListMeta interface.
 */
export function instanceOfListMeta(value: object): value is ListMeta {
    return true;
}

export function ListMetaFromJSON(json: any): ListMeta {
    return ListMetaFromJSONTyped(json, false);
}

export function ListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['total_count'] == null ? undefined : json['total_count'],
    };
}

export function ListMetaToJSON(json: any): ListMeta {
    return ListMetaToJSONTyped(json, false);
}

export function ListMetaToJSONTyped(value?: ListMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total_count': value['totalCount'],
    };
}

