/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { THSensor } from './THSensor';
import {
    THSensorFromJSON,
    THSensorFromJSONTyped,
    THSensorToJSON,
    THSensorToJSONTyped,
} from './THSensor';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListTHSensor200Response
 */
export interface ListTHSensor200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListTHSensor200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<THSensor>}
     * @memberof ListTHSensor200Response
     */
    objects: Array<THSensor>;
}

/**
 * Check if a given object implements the ListTHSensor200Response interface.
 */
export function instanceOfListTHSensor200Response(value: object): value is ListTHSensor200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListTHSensor200ResponseFromJSON(json: any): ListTHSensor200Response {
    return ListTHSensor200ResponseFromJSONTyped(json, false);
}

export function ListTHSensor200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTHSensor200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(THSensorFromJSON)),
    };
}

export function ListTHSensor200ResponseToJSON(json: any): ListTHSensor200Response {
    return ListTHSensor200ResponseToJSONTyped(json, false);
}

export function ListTHSensor200ResponseToJSONTyped(value?: ListTHSensor200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(THSensorToJSON)),
    };
}

