/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorResync } from './SensorResync';
import {
    SensorResyncFromJSON,
    SensorResyncFromJSONTyped,
    SensorResyncToJSON,
    SensorResyncToJSONTyped,
} from './SensorResync';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListSensorResync200Response
 */
export interface ListSensorResync200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListSensorResync200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<SensorResync>}
     * @memberof ListSensorResync200Response
     */
    objects: Array<SensorResync>;
}

/**
 * Check if a given object implements the ListSensorResync200Response interface.
 */
export function instanceOfListSensorResync200Response(value: object): value is ListSensorResync200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListSensorResync200ResponseFromJSON(json: any): ListSensorResync200Response {
    return ListSensorResync200ResponseFromJSONTyped(json, false);
}

export function ListSensorResync200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSensorResync200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(SensorResyncFromJSON)),
    };
}

export function ListSensorResync200ResponseToJSON(json: any): ListSensorResync200Response {
    return ListSensorResync200ResponseToJSONTyped(json, false);
}

export function ListSensorResync200ResponseToJSONTyped(value?: ListSensorResync200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(SensorResyncToJSON)),
    };
}

