/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListProfile200Response
 */
export interface ListProfile200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListProfile200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<Profile>}
     * @memberof ListProfile200Response
     */
    objects: Array<Profile>;
}

/**
 * Check if a given object implements the ListProfile200Response interface.
 */
export function instanceOfListProfile200Response(value: object): value is ListProfile200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListProfile200ResponseFromJSON(json: any): ListProfile200Response {
    return ListProfile200ResponseFromJSONTyped(json, false);
}

export function ListProfile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProfile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(ProfileFromJSON)),
    };
}

export function ListProfile200ResponseToJSON(json: any): ListProfile200Response {
    return ListProfile200ResponseToJSONTyped(json, false);
}

export function ListProfile200ResponseToJSONTyped(value?: ListProfile200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(ProfileToJSON)),
    };
}

