/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstantProfile } from './InstantProfile';
import {
    InstantProfileFromJSON,
    InstantProfileFromJSONTyped,
    InstantProfileToJSON,
    InstantProfileToJSONTyped,
} from './InstantProfile';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListInstantProfile200Response
 */
export interface ListInstantProfile200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListInstantProfile200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<InstantProfile>}
     * @memberof ListInstantProfile200Response
     */
    objects: Array<InstantProfile>;
}

/**
 * Check if a given object implements the ListInstantProfile200Response interface.
 */
export function instanceOfListInstantProfile200Response(value: object): value is ListInstantProfile200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListInstantProfile200ResponseFromJSON(json: any): ListInstantProfile200Response {
    return ListInstantProfile200ResponseFromJSONTyped(json, false);
}

export function ListInstantProfile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInstantProfile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(InstantProfileFromJSON)),
    };
}

export function ListInstantProfile200ResponseToJSON(json: any): ListInstantProfile200Response {
    return ListInstantProfile200ResponseToJSONTyped(json, false);
}

export function ListInstantProfile200ResponseToJSONTyped(value?: ListInstantProfile200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(InstantProfileToJSON)),
    };
}

