/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayType } from './DayType';
import {
    DayTypeFromJSON,
    DayTypeFromJSONTyped,
    DayTypeToJSON,
    DayTypeToJSONTyped,
} from './DayType';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListDayType200Response
 */
export interface ListDayType200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListDayType200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<DayType>}
     * @memberof ListDayType200Response
     */
    objects: Array<DayType>;
}

/**
 * Check if a given object implements the ListDayType200Response interface.
 */
export function instanceOfListDayType200Response(value: object): value is ListDayType200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListDayType200ResponseFromJSON(json: any): ListDayType200Response {
    return ListDayType200ResponseFromJSONTyped(json, false);
}

export function ListDayType200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDayType200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(DayTypeFromJSON)),
    };
}

export function ListDayType200ResponseToJSON(json: any): ListDayType200Response {
    return ListDayType200ResponseToJSONTyped(json, false);
}

export function ListDayType200ResponseToJSONTyped(value?: ListDayType200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(DayTypeToJSON)),
    };
}

