/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Control } from './Control';
import {
    ControlFromJSON,
    ControlFromJSONTyped,
    ControlToJSON,
    ControlToJSONTyped,
} from './Control';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';

/**
 * 
 * @export
 * @interface ListControl200Response
 */
export interface ListControl200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListControl200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<Control>}
     * @memberof ListControl200Response
     */
    objects: Array<Control>;
}

/**
 * Check if a given object implements the ListControl200Response interface.
 */
export function instanceOfListControl200Response(value: object): value is ListControl200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListControl200ResponseFromJSON(json: any): ListControl200Response {
    return ListControl200ResponseFromJSONTyped(json, false);
}

export function ListControl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListControl200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(ControlFromJSON)),
    };
}

export function ListControl200ResponseToJSON(json: any): ListControl200Response {
    return ListControl200ResponseToJSONTyped(json, false);
}

export function ListControl200ResponseToJSONTyped(value?: ListControl200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(ControlToJSON)),
    };
}

