/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface ListSession200Response
 */
export interface ListSession200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListSession200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<Session>}
     * @memberof ListSession200Response
     */
    objects: Array<Session>;
}

/**
 * Check if a given object implements the ListSession200Response interface.
 */
export function instanceOfListSession200Response(value: object): value is ListSession200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListSession200ResponseFromJSON(json: any): ListSession200Response {
    return ListSession200ResponseFromJSONTyped(json, false);
}

export function ListSession200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSession200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(SessionFromJSON)),
    };
}

export function ListSession200ResponseToJSON(json: any): ListSession200Response {
    return ListSession200ResponseToJSONTyped(json, false);
}

export function ListSession200ResponseToJSONTyped(value?: ListSession200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(SessionToJSON)),
    };
}

