/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListMeta } from './ListMeta';
import {
    ListMetaFromJSON,
    ListMetaFromJSONTyped,
    ListMetaToJSON,
    ListMetaToJSONTyped,
} from './ListMeta';
import type { Sensor } from './Sensor';
import {
    SensorFromJSON,
    SensorFromJSONTyped,
    SensorToJSON,
    SensorToJSONTyped,
} from './Sensor';

/**
 * 
 * @export
 * @interface ListSensor200Response
 */
export interface ListSensor200Response {
    /**
     * 
     * @type {ListMeta}
     * @memberof ListSensor200Response
     */
    meta: ListMeta;
    /**
     * 
     * @type {Array<Sensor>}
     * @memberof ListSensor200Response
     */
    objects: Array<Sensor>;
}

/**
 * Check if a given object implements the ListSensor200Response interface.
 */
export function instanceOfListSensor200Response(value: object): value is ListSensor200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListSensor200ResponseFromJSON(json: any): ListSensor200Response {
    return ListSensor200ResponseFromJSONTyped(json, false);
}

export function ListSensor200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSensor200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': ListMetaFromJSON(json['meta']),
        'objects': ((json['objects'] as Array<any>).map(SensorFromJSON)),
    };
}

export function ListSensor200ResponseToJSON(json: any): ListSensor200Response {
    return ListSensor200ResponseToJSONTyped(json, false);
}

export function ListSensor200ResponseToJSONTyped(value?: ListSensor200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': ListMetaToJSON(value['meta']),
        'objects': ((value['objects'] as Array<any>).map(SensorToJSON)),
    };
}

