/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchInstantProfileRequest
 */
export interface PatchInstantProfileRequest {
    /**
     * name
     * @type {string}
     * @memberof PatchInstantProfileRequest
     */
    name?: string;
    /**
     * active
     * @type {boolean}
     * @memberof PatchInstantProfileRequest
     */
    active?: boolean;
}

/**
 * Check if a given object implements the PatchInstantProfileRequest interface.
 */
export function instanceOfPatchInstantProfileRequest(value: object): value is PatchInstantProfileRequest {
    return true;
}

export function PatchInstantProfileRequestFromJSON(json: any): PatchInstantProfileRequest {
    return PatchInstantProfileRequestFromJSONTyped(json, false);
}

export function PatchInstantProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchInstantProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function PatchInstantProfileRequestToJSON(json: any): PatchInstantProfileRequest {
    return PatchInstantProfileRequestToJSONTyped(json, false);
}

export function PatchInstantProfileRequestToJSONTyped(value?: PatchInstantProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'active': value['active'],
    };
}

