/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchProfileRequest
 */
export interface PatchProfileRequest {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof PatchProfileRequest
     */
    control?: string;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof PatchProfileRequest
     */
    daytype?: string;
    /**
     * ID
     * @type {number}
     * @memberof PatchProfileRequest
     */
    id?: number;
    /**
     * start
     * @type {string}
     * @memberof PatchProfileRequest
     */
    start?: string;
    /**
     * target temp
     * @type {number}
     * @memberof PatchProfileRequest
     */
    targetTemp?: number | null;
}

/**
 * Check if a given object implements the PatchProfileRequest interface.
 */
export function instanceOfPatchProfileRequest(value: object): value is PatchProfileRequest {
    return true;
}

export function PatchProfileRequestFromJSON(json: any): PatchProfileRequest {
    return PatchProfileRequestFromJSONTyped(json, false);
}

export function PatchProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'control': json['control'] == null ? undefined : json['control'],
        'daytype': json['daytype'] == null ? undefined : json['daytype'],
        'id': json['id'] == null ? undefined : json['id'],
        'start': json['start'] == null ? undefined : json['start'],
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
    };
}

export function PatchProfileRequestToJSON(json: any): PatchProfileRequest {
    return PatchProfileRequestToJSONTyped(json, false);
}

export function PatchProfileRequestToJSONTyped(value?: PatchProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'control': value['control'],
        'daytype': value['daytype'],
        'id': value['id'],
        'start': value['start'],
        'target_temp': value['targetTemp'],
    };
}

