/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchDayTypeRequest
 */
export interface PatchDayTypeRequest {
    /**
     * ID
     * @type {number}
     * @memberof PatchDayTypeRequest
     */
    id?: number;
    /**
     * name
     * @type {string}
     * @memberof PatchDayTypeRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the PatchDayTypeRequest interface.
 */
export function instanceOfPatchDayTypeRequest(value: object): value is PatchDayTypeRequest {
    return true;
}

export function PatchDayTypeRequestFromJSON(json: any): PatchDayTypeRequest {
    return PatchDayTypeRequestFromJSONTyped(json, false);
}

export function PatchDayTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchDayTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PatchDayTypeRequestToJSON(json: any): PatchDayTypeRequest {
    return PatchDayTypeRequestToJSONTyped(json, false);
}

export function PatchDayTypeRequestToJSONTyped(value?: PatchDayTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

