/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchScheduledOverrideRequest
 */
export interface PatchScheduledOverrideRequest {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof PatchScheduledOverrideRequest
     */
    control?: string;
    /**
     * ID
     * @type {number}
     * @memberof PatchScheduledOverrideRequest
     */
    id?: number;
    /**
     * start
     * @type {Date}
     * @memberof PatchScheduledOverrideRequest
     */
    start?: Date;
    /**
     * end
     * @type {Date}
     * @memberof PatchScheduledOverrideRequest
     */
    end?: Date;
    /**
     * target temp
     * @type {number}
     * @memberof PatchScheduledOverrideRequest
     */
    targetTemp?: number;
}

/**
 * Check if a given object implements the PatchScheduledOverrideRequest interface.
 */
export function instanceOfPatchScheduledOverrideRequest(value: object): value is PatchScheduledOverrideRequest {
    return true;
}

export function PatchScheduledOverrideRequestFromJSON(json: any): PatchScheduledOverrideRequest {
    return PatchScheduledOverrideRequestFromJSONTyped(json, false);
}

export function PatchScheduledOverrideRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchScheduledOverrideRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'control': json['control'] == null ? undefined : json['control'],
        'id': json['id'] == null ? undefined : json['id'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
    };
}

export function PatchScheduledOverrideRequestToJSON(json: any): PatchScheduledOverrideRequest {
    return PatchScheduledOverrideRequestToJSONTyped(json, false);
}

export function PatchScheduledOverrideRequestToJSONTyped(value?: PatchScheduledOverrideRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'control': value['control'],
        'id': value['id'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'target_temp': value['targetTemp'],
    };
}

