/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchSensorRequest
 */
export interface PatchSensorRequest {
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof PatchSensorRequest
     */
    vcc?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof PatchSensorRequest
     */
    rssi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof PatchSensorRequest
     */
    lqi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof PatchSensorRequest
     */
    interval?: number | null;
    /**
     * name
     * @type {string}
     * @memberof PatchSensorRequest
     */
    name?: string;
    /**
     * last tsf
     * @type {number}
     * @memberof PatchSensorRequest
     */
    lastTsf?: number | null;
}

/**
 * Check if a given object implements the PatchSensorRequest interface.
 */
export function instanceOfPatchSensorRequest(value: object): value is PatchSensorRequest {
    return true;
}

export function PatchSensorRequestFromJSON(json: any): PatchSensorRequest {
    return PatchSensorRequestFromJSONTyped(json, false);
}

export function PatchSensorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchSensorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vcc': json['vcc'] == null ? undefined : json['vcc'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'lqi': json['lqi'] == null ? undefined : json['lqi'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'name': json['name'] == null ? undefined : json['name'],
        'lastTsf': json['last_tsf'] == null ? undefined : json['last_tsf'],
    };
}

export function PatchSensorRequestToJSON(json: any): PatchSensorRequest {
    return PatchSensorRequestToJSONTyped(json, false);
}

export function PatchSensorRequestToJSONTyped(value?: PatchSensorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vcc': value['vcc'],
        'rssi': value['rssi'],
        'lqi': value['lqi'],
        'interval': value['interval'],
        'name': value['name'],
        'last_tsf': value['lastTsf'],
    };
}

