/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchControlRequest
 */
export interface PatchControlRequest {
    /**
     * kp
     * @type {number}
     * @memberof PatchControlRequest
     */
    kp?: number;
    /**
     * ki
     * @type {number}
     * @memberof PatchControlRequest
     */
    ki?: number;
    /**
     * kd
     * @type {number}
     * @memberof PatchControlRequest
     */
    kd?: number;
    /**
     * intabsmax
     * @type {number}
     * @memberof PatchControlRequest
     */
    intabsmax?: number | null;
}

/**
 * Check if a given object implements the PatchControlRequest interface.
 */
export function instanceOfPatchControlRequest(value: object): value is PatchControlRequest {
    return true;
}

export function PatchControlRequestFromJSON(json: any): PatchControlRequest {
    return PatchControlRequestFromJSONTyped(json, false);
}

export function PatchControlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchControlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kp': json['kp'] == null ? undefined : json['kp'],
        'ki': json['ki'] == null ? undefined : json['ki'],
        'kd': json['kd'] == null ? undefined : json['kd'],
        'intabsmax': json['intabsmax'] == null ? undefined : json['intabsmax'],
    };
}

export function PatchControlRequestToJSON(json: any): PatchControlRequest {
    return PatchControlRequestToJSONTyped(json, false);
}

export function PatchControlRequestToJSONTyped(value?: PatchControlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kp': value['kp'],
        'ki': value['ki'],
        'kd': value['kd'],
        'intabsmax': value['intabsmax'],
    };
}

