/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileW
 */
export interface ProfileW {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ProfileW
     */
    control: string;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ProfileW
     */
    daytype: string;
    /**
     * ID
     * @type {number}
     * @memberof ProfileW
     */
    id: number;
    /**
     * start
     * @type {string}
     * @memberof ProfileW
     */
    start: string;
    /**
     * target temp
     * @type {number}
     * @memberof ProfileW
     */
    targetTemp?: number | null;
}

/**
 * Check if a given object implements the ProfileW interface.
 */
export function instanceOfProfileW(value: object): value is ProfileW {
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('daytype' in value) || value['daytype'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function ProfileWFromJSON(json: any): ProfileW {
    return ProfileWFromJSONTyped(json, false);
}

export function ProfileWFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileW {
    if (json == null) {
        return json;
    }
    return {
        
        'control': json['control'],
        'daytype': json['daytype'],
        'id': json['id'],
        'start': json['start'],
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
    };
}

export function ProfileWToJSON(json: any): ProfileW {
    return ProfileWToJSONTyped(json, false);
}

export function ProfileWToJSONTyped(value?: ProfileW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'control': value['control'],
        'daytype': value['daytype'],
        'id': value['id'],
        'start': value['start'],
        'target_temp': value['targetTemp'],
    };
}

