/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * resource uri
     * @type {string}
     * @memberof Profile
     */
    resourceUri: string;
    /**
     * ID
     * @type {number}
     * @memberof Profile
     */
    id: number;
    /**
     * resource uri
     * @type {string}
     * @memberof Profile
     */
    control: string;
    /**
     * resource uri
     * @type {string}
     * @memberof Profile
     */
    daytype: string;
    /**
     * start
     * @type {string}
     * @memberof Profile
     */
    start: string;
    /**
     * target temp
     * @type {number}
     * @memberof Profile
     */
    targetTemp?: number | null;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('daytype' in value) || value['daytype'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
        'control': json['control'],
        'daytype': json['daytype'],
        'start': json['start'],
        'targetTemp': json['target_temp'] == null ? undefined : json['target_temp'],
    };
}

export function ProfileToJSON(json: any): Profile {
    return ProfileToJSONTyped(json, false);
}

export function ProfileToJSONTyped(value?: Profile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
        'control': value['control'],
        'daytype': value['daytype'],
        'start': value['start'],
        'target_temp': value['targetTemp'],
    };
}

