/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileR
 */
export interface ProfileR {
    /**
     * resource uri
     * @type {string}
     * @memberof ProfileR
     */
    resourceUri: string;
    /**
     * ID
     * @type {number}
     * @memberof ProfileR
     */
    id: number;
}

/**
 * Check if a given object implements the ProfileR interface.
 */
export function instanceOfProfileR(value: object): value is ProfileR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ProfileRFromJSON(json: any): ProfileR {
    return ProfileRFromJSONTyped(json, false);
}

export function ProfileRFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
    };
}

export function ProfileRToJSON(json: any): ProfileR {
    return ProfileRToJSONTyped(json, false);
}

export function ProfileRToJSONTyped(value?: ProfileR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
    };
}

