/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledOverrideW
 */
export interface ScheduledOverrideW {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof ScheduledOverrideW
     */
    control: string;
    /**
     * ID
     * @type {number}
     * @memberof ScheduledOverrideW
     */
    id: number;
    /**
     * start
     * @type {Date}
     * @memberof ScheduledOverrideW
     */
    start: Date;
    /**
     * end
     * @type {Date}
     * @memberof ScheduledOverrideW
     */
    end: Date;
    /**
     * target temp
     * @type {number}
     * @memberof ScheduledOverrideW
     */
    targetTemp: number;
}

/**
 * Check if a given object implements the ScheduledOverrideW interface.
 */
export function instanceOfScheduledOverrideW(value: object): value is ScheduledOverrideW {
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('targetTemp' in value) || value['targetTemp'] === undefined) return false;
    return true;
}

export function ScheduledOverrideWFromJSON(json: any): ScheduledOverrideW {
    return ScheduledOverrideWFromJSONTyped(json, false);
}

export function ScheduledOverrideWFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledOverrideW {
    if (json == null) {
        return json;
    }
    return {
        
        'control': json['control'],
        'id': json['id'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'targetTemp': json['target_temp'],
    };
}

export function ScheduledOverrideWToJSON(json: any): ScheduledOverrideW {
    return ScheduledOverrideWToJSONTyped(json, false);
}

export function ScheduledOverrideWToJSONTyped(value?: ScheduledOverrideW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'control': value['control'],
        'id': value['id'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
        'target_temp': value['targetTemp'],
    };
}

