/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledOverrideR
 */
export interface ScheduledOverrideR {
    /**
     * ID
     * @type {number}
     * @memberof ScheduledOverrideR
     */
    id: number;
}

/**
 * Check if a given object implements the ScheduledOverrideR interface.
 */
export function instanceOfScheduledOverrideR(value: object): value is ScheduledOverrideR {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ScheduledOverrideRFromJSON(json: any): ScheduledOverrideR {
    return ScheduledOverrideRFromJSONTyped(json, false);
}

export function ScheduledOverrideRFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledOverrideR {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ScheduledOverrideRToJSON(json: any): ScheduledOverrideR {
    return ScheduledOverrideRToJSONTyped(json, false);
}

export function ScheduledOverrideRToJSONTyped(value?: ScheduledOverrideR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

