/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledOverride
 */
export interface ScheduledOverride {
    /**
     * resource uri
     * @type {string}
     * @memberof ScheduledOverride
     */
    resourceUri: string;
    /**
     * ID
     * @type {number}
     * @memberof ScheduledOverride
     */
    id: number;
    /**
     * resource uri
     * @type {string}
     * @memberof ScheduledOverride
     */
    control: string;
    /**
     * start
     * @type {Date}
     * @memberof ScheduledOverride
     */
    start: Date;
    /**
     * end
     * @type {Date}
     * @memberof ScheduledOverride
     */
    end: Date;
    /**
     * target temp
     * @type {number}
     * @memberof ScheduledOverride
     */
    targetTemp: number;
}

/**
 * Check if a given object implements the ScheduledOverride interface.
 */
export function instanceOfScheduledOverride(value: object): value is ScheduledOverride {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('control' in value) || value['control'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('targetTemp' in value) || value['targetTemp'] === undefined) return false;
    return true;
}

export function ScheduledOverrideFromJSON(json: any): ScheduledOverride {
    return ScheduledOverrideFromJSONTyped(json, false);
}

export function ScheduledOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
        'control': json['control'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'targetTemp': json['target_temp'],
    };
}

export function ScheduledOverrideToJSON(json: any): ScheduledOverride {
    return ScheduledOverrideToJSONTyped(json, false);
}

export function ScheduledOverrideToJSONTyped(value?: ScheduledOverride | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
        'control': value['control'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
        'target_temp': value['targetTemp'],
    };
}

