/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorResyncR
 */
export interface SensorResyncR {
    /**
     * resource uri
     * @type {string}
     * @memberof SensorResyncR
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof SensorResyncR
     */
    ts: Date;
    /**
     * ID
     * @type {number}
     * @memberof SensorResyncR
     */
    id: number;
}

/**
 * Check if a given object implements the SensorResyncR interface.
 */
export function instanceOfSensorResyncR(value: object): value is SensorResyncR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SensorResyncRFromJSON(json: any): SensorResyncR {
    return SensorResyncRFromJSONTyped(json, false);
}

export function SensorResyncRFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorResyncR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'ts': (new Date(json['ts'])),
        'id': json['id'],
    };
}

export function SensorResyncRToJSON(json: any): SensorResyncR {
    return SensorResyncRToJSONTyped(json, false);
}

export function SensorResyncRToJSONTyped(value?: SensorResyncR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'ts': value['ts'].toISOString(),
        'id': value['id'],
    };
}

