/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorResync
 */
export interface SensorResync {
    /**
     * resource uri
     * @type {string}
     * @memberof SensorResync
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {Date}
     * @memberof SensorResync
     */
    ts: Date;
    /**
     * ID
     * @type {number}
     * @memberof SensorResync
     */
    id: number;
    /**
     * resource uri
     * @type {string}
     * @memberof SensorResync
     */
    sensor: string;
}

/**
 * Check if a given object implements the SensorResync interface.
 */
export function instanceOfSensorResync(value: object): value is SensorResync {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sensor' in value) || value['sensor'] === undefined) return false;
    return true;
}

export function SensorResyncFromJSON(json: any): SensorResync {
    return SensorResyncFromJSONTyped(json, false);
}

export function SensorResyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorResync {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'ts': (new Date(json['ts'])),
        'id': json['id'],
        'sensor': json['sensor'],
    };
}

export function SensorResyncToJSON(json: any): SensorResync {
    return SensorResyncToJSONTyped(json, false);
}

export function SensorResyncToJSONTyped(value?: SensorResync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'ts': value['ts'].toISOString(),
        'id': value['id'],
        'sensor': value['sensor'],
    };
}

