/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sensor
 */
export interface Sensor {
    /**
     * resource uri
     * @type {string}
     * @memberof Sensor
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {boolean}
     * @memberof Sensor
     */
    valid?: boolean | null;
    /**
     * resource uri
     * @type {string}
     * @memberof Sensor
     */
    sensorResync?: string;
    /**
     * resource uri
     * @type {string}
     * @memberof Sensor
     */
    thsensor?: string;
    /**
     * id
     * @type {number}
     * @memberof Sensor
     */
    id: number;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Sensor
     */
    vcc?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Sensor
     */
    rssi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Sensor
     */
    lqi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Sensor
     */
    interval?: number | null;
    /**
     * name
     * @type {string}
     * @memberof Sensor
     */
    name: string;
    /**
     * last tsf
     * @type {number}
     * @memberof Sensor
     */
    lastTsf?: number | null;
}

/**
 * Check if a given object implements the Sensor interface.
 */
export function instanceOfSensor(value: object): value is Sensor {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SensorFromJSON(json: any): Sensor {
    return SensorFromJSONTyped(json, false);
}

export function SensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sensor {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'valid': json['valid'] == null ? undefined : json['valid'],
        'sensorResync': json['sensor_resync'] == null ? undefined : json['sensor_resync'],
        'thsensor': json['thsensor'] == null ? undefined : json['thsensor'],
        'id': json['id'],
        'vcc': json['vcc'] == null ? undefined : json['vcc'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'lqi': json['lqi'] == null ? undefined : json['lqi'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'name': json['name'],
        'lastTsf': json['last_tsf'] == null ? undefined : json['last_tsf'],
    };
}

export function SensorToJSON(json: any): Sensor {
    return SensorToJSONTyped(json, false);
}

export function SensorToJSONTyped(value?: Sensor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'valid': value['valid'],
        'sensor_resync': value['sensorResync'],
        'thsensor': value['thsensor'],
        'id': value['id'],
        'vcc': value['vcc'],
        'rssi': value['rssi'],
        'lqi': value['lqi'],
        'interval': value['interval'],
        'name': value['name'],
        'last_tsf': value['lastTsf'],
    };
}

