/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorR
 */
export interface SensorR {
    /**
     * resource uri
     * @type {string}
     * @memberof SensorR
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {boolean}
     * @memberof SensorR
     */
    valid?: boolean | null;
    /**
     * resource uri
     * @type {string}
     * @memberof SensorR
     */
    sensorResync?: string;
    /**
     * resource uri
     * @type {string}
     * @memberof SensorR
     */
    thsensor?: string;
    /**
     * id
     * @type {number}
     * @memberof SensorR
     */
    id: number;
}

/**
 * Check if a given object implements the SensorR interface.
 */
export function instanceOfSensorR(value: object): value is SensorR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SensorRFromJSON(json: any): SensorR {
    return SensorRFromJSONTyped(json, false);
}

export function SensorRFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'valid': json['valid'] == null ? undefined : json['valid'],
        'sensorResync': json['sensor_resync'] == null ? undefined : json['sensor_resync'],
        'thsensor': json['thsensor'] == null ? undefined : json['thsensor'],
        'id': json['id'],
    };
}

export function SensorRToJSON(json: any): SensorR {
    return SensorRToJSONTyped(json, false);
}

export function SensorRToJSONTyped(value?: SensorR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'valid': value['valid'],
        'sensor_resync': value['sensorResync'],
        'thsensor': value['thsensor'],
        'id': value['id'],
    };
}

