/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorResyncW
 */
export interface SensorResyncW {
    /**
     * resource uri
     * @type {string}
     * @memberof SensorResyncW
     */
    sensor: string;
}

/**
 * Check if a given object implements the SensorResyncW interface.
 */
export function instanceOfSensorResyncW(value: object): value is SensorResyncW {
    if (!('sensor' in value) || value['sensor'] === undefined) return false;
    return true;
}

export function SensorResyncWFromJSON(json: any): SensorResyncW {
    return SensorResyncWFromJSONTyped(json, false);
}

export function SensorResyncWFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorResyncW {
    if (json == null) {
        return json;
    }
    return {
        
        'sensor': json['sensor'],
    };
}

export function SensorResyncWToJSON(json: any): SensorResyncW {
    return SensorResyncWToJSONTyped(json, false);
}

export function SensorResyncWToJSONTyped(value?: SensorResyncW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensor': value['sensor'],
    };
}

