/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorW
 */
export interface SensorW {
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof SensorW
     */
    vcc?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof SensorW
     */
    rssi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof SensorW
     */
    lqi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof SensorW
     */
    interval?: number | null;
    /**
     * name
     * @type {string}
     * @memberof SensorW
     */
    name: string;
    /**
     * last tsf
     * @type {number}
     * @memberof SensorW
     */
    lastTsf?: number | null;
}

/**
 * Check if a given object implements the SensorW interface.
 */
export function instanceOfSensorW(value: object): value is SensorW {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SensorWFromJSON(json: any): SensorW {
    return SensorWFromJSONTyped(json, false);
}

export function SensorWFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorW {
    if (json == null) {
        return json;
    }
    return {
        
        'vcc': json['vcc'] == null ? undefined : json['vcc'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'lqi': json['lqi'] == null ? undefined : json['lqi'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'name': json['name'],
        'lastTsf': json['last_tsf'] == null ? undefined : json['last_tsf'],
    };
}

export function SensorWToJSON(json: any): SensorW {
    return SensorWToJSONTyped(json, false);
}

export function SensorWToJSONTyped(value?: SensorW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vcc': value['vcc'],
        'rssi': value['rssi'],
        'lqi': value['lqi'],
        'interval': value['interval'],
        'name': value['name'],
        'last_tsf': value['lastTsf'],
    };
}

