/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionR
 */
export interface SessionR {
    /**
     * resource uri
     * @type {string}
     * @memberof SessionR
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof SessionR
     */
    id: number;
    /**
     * NO_DESCRIPTION
     * @type {boolean}
     * @memberof SessionR
     */
    isAdmin: boolean;
}

/**
 * Check if a given object implements the SessionR interface.
 */
export function instanceOfSessionR(value: object): value is SessionR {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    return true;
}

export function SessionRFromJSON(json: any): SessionR {
    return SessionRFromJSONTyped(json, false);
}

export function SessionRFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionR {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
        'isAdmin': json['is_admin'],
    };
}

export function SessionRToJSON(json: any): SessionR {
    return SessionRToJSONTyped(json, false);
}

export function SessionRToJSONTyped(value?: SessionR | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
        'is_admin': value['isAdmin'],
    };
}

