/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * resource uri
     * @type {string}
     * @memberof Session
     */
    resourceUri: string;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof Session
     */
    id: number;
    /**
     * NO_DESCRIPTION
     * @type {boolean}
     * @memberof Session
     */
    isAdmin: boolean;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof Session
     */
    username: string;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof Session
     */
    password?: string | null;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): value is Session {
    if (!('resourceUri' in value) || value['resourceUri'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceUri': json['resource_uri'],
        'id': json['id'],
        'isAdmin': json['is_admin'],
        'username': json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function SessionToJSON(json: any): Session {
    return SessionToJSONTyped(json, false);
}

export function SessionToJSONTyped(value?: Session | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_uri': value['resourceUri'],
        'id': value['id'],
        'is_admin': value['isAdmin'],
        'username': value['username'],
        'password': value['password'],
    };
}

