/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionW
 */
export interface SessionW {
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof SessionW
     */
    username: string;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof SessionW
     */
    password?: string | null;
}

/**
 * Check if a given object implements the SessionW interface.
 */
export function instanceOfSessionW(value: object): value is SessionW {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function SessionWFromJSON(json: any): SessionW {
    return SessionWFromJSONTyped(json, false);
}

export function SessionWFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionW {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function SessionWToJSON(json: any): SessionW {
    return SessionWToJSONTyped(json, false);
}

export function SessionWToJSONTyped(value?: SessionW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

