/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface THSensorW
 */
export interface THSensorW {
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    vcc?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    rssi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    lqi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    interval?: number | null;
    /**
     * name
     * @type {string}
     * @memberof THSensorW
     */
    name: string;
    /**
     * last tsf
     * @type {number}
     * @memberof THSensorW
     */
    lastTsf?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    temperature?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensorW
     */
    humidity?: number | null;
    /**
     * last seq
     * @type {number}
     * @memberof THSensorW
     */
    lastSeq?: number | null;
}

/**
 * Check if a given object implements the THSensorW interface.
 */
export function instanceOfTHSensorW(value: object): value is THSensorW {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function THSensorWFromJSON(json: any): THSensorW {
    return THSensorWFromJSONTyped(json, false);
}

export function THSensorWFromJSONTyped(json: any, ignoreDiscriminator: boolean): THSensorW {
    if (json == null) {
        return json;
    }
    return {
        
        'vcc': json['vcc'] == null ? undefined : json['vcc'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'lqi': json['lqi'] == null ? undefined : json['lqi'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'name': json['name'],
        'lastTsf': json['last_tsf'] == null ? undefined : json['last_tsf'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'humidity': json['humidity'] == null ? undefined : json['humidity'],
        'lastSeq': json['last_seq'] == null ? undefined : json['last_seq'],
    };
}

export function THSensorWToJSON(json: any): THSensorW {
    return THSensorWToJSONTyped(json, false);
}

export function THSensorWToJSONTyped(value?: THSensorW | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vcc': value['vcc'],
        'rssi': value['rssi'],
        'lqi': value['lqi'],
        'interval': value['interval'],
        'name': value['name'],
        'last_tsf': value['lastTsf'],
        'temperature': value['temperature'],
        'humidity': value['humidity'],
        'last_seq': value['lastSeq'],
    };
}

