/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface THSensor
 */
export interface THSensor {
    /**
     * NO_DESCRIPTION
     * @type {boolean}
     * @memberof THSensor
     */
    valid?: boolean | null;
    /**
     * NO_DESCRIPTION
     * @type {string}
     * @memberof THSensor
     */
    sensorResync?: string | null;
    /**
     * id
     * @type {number}
     * @memberof THSensor
     */
    id: number;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    vcc?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    rssi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    lqi?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    interval?: number | null;
    /**
     * name
     * @type {string}
     * @memberof THSensor
     */
    name: string;
    /**
     * last tsf
     * @type {number}
     * @memberof THSensor
     */
    lastTsf?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    temperature?: number | null;
    /**
     * NO_DESCRIPTION
     * @type {number}
     * @memberof THSensor
     */
    humidity?: number | null;
    /**
     * last seq
     * @type {number}
     * @memberof THSensor
     */
    lastSeq?: number | null;
}

/**
 * Check if a given object implements the THSensor interface.
 */
export function instanceOfTHSensor(value: object): value is THSensor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function THSensorFromJSON(json: any): THSensor {
    return THSensorFromJSONTyped(json, false);
}

export function THSensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): THSensor {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'] == null ? undefined : json['valid'],
        'sensorResync': json['sensor_resync'] == null ? undefined : json['sensor_resync'],
        'id': json['id'],
        'vcc': json['vcc'] == null ? undefined : json['vcc'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'lqi': json['lqi'] == null ? undefined : json['lqi'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'name': json['name'],
        'lastTsf': json['last_tsf'] == null ? undefined : json['last_tsf'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'humidity': json['humidity'] == null ? undefined : json['humidity'],
        'lastSeq': json['last_seq'] == null ? undefined : json['last_seq'],
    };
}

export function THSensorToJSON(json: any): THSensor {
    return THSensorToJSONTyped(json, false);
}

export function THSensorToJSONTyped(value?: THSensor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'sensor_resync': value['sensorResync'],
        'id': value['id'],
        'vcc': value['vcc'],
        'rssi': value['rssi'],
        'lqi': value['lqi'],
        'interval': value['interval'],
        'name': value['name'],
        'last_tsf': value['lastTsf'],
        'temperature': value['temperature'],
        'humidity': value['humidity'],
        'last_seq': value['lastSeq'],
    };
}

