kind: pipeline
name: build
type: kubernetes

resources:
  requests:
    memory: 384Mi

steps:
- name: versions
  image: alpine:3.14
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - V=$(git describe --tags HEAD)
  - 'echo "export default \\"$V\\";" > www/version.js'
  - 'sed -i -e "/^const cacheVersion/s/ =.*/ = \\"$V\\";/" www/sw.js'

- name: api
  image: plugins/docker
  pull: always
  settings:
    target: api
    repo: ghcr.io/rkojedzinszky/thermo-center-api
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

- name: golang-build
  image: golang:1.16-alpine
  pull: always
  commands:
  - mkdir -p ${GOPATH}/src/github.com/rkojedzinszky
  - ln -sf $(pwd) ${GOPATH}/src/github.com/rkojedzinszky/thermo-center
  - cd ${GOPATH}/src/github.com/rkojedzinszky/thermo-center
  - mkdir bin
  - CGO_ENABLED=0 go build -ldflags -s -o bin/grpcserver ./cmd/grpcserver
  - CGO_ENABLED=0 go build -ldflags -s -o bin/ws ./ws
  - CGO_ENABLED=0 go build -ldflags -s -o bin/receiver ./cmd/receiver

- name: receiver
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.receiver
    repo: ghcr.io/rkojedzinszky/thermo-center-receiver
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

- name: grpcserver
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.grpcserver
    repo: ghcr.io/rkojedzinszky/thermo-center-grpcserver
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

- name: ws
  image: plugins/docker
  pull: always
  settings:
    dockerfile: Dockerfile.ws
    repo: ghcr.io/rkojedzinszky/thermo-center-ws
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

- name: ui
  image: plugins/docker
  pull: always
  settings:
    target: ui
    repo: ghcr.io/rkojedzinszky/thermo-center-ui
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: docker
  temp: {}
