# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0010_auto_20170429_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantprofileentry',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql='create unique index heatcontrol_instantprofileentry_control_active on heatcontrol_instantprofileentry (control_id) where active = true',
            reverse_sql='drop index heatcontrol_instantprofileentry_control_active',
        ),
    ]
