# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:50
from __future__ import unicode_literals

from django.db import migrations

def migrate_fwd(apps, schema_editor):
    InstantProfileEntry = apps.get_model('heatcontrol', 'InstantProfileEntry')
    InstantOverride = apps.get_model('heatcontrol', 'InstantOverride')

    InstantProfileEntry.objects.all().update(active=False)
    for o in InstantOverride.objects.all():
        pe = InstantProfileEntry.objects.get(profile=o.profile, control=o.control)
        pe.active = True
        pe.save()
        o.delete()

def migrate_rev(apps, schema_editor):
    InstantProfileEntry = apps.get_model('heatcontrol', 'InstantProfileEntry')
    InstantOverride = apps.get_model('heatcontrol', 'InstantOverride')

    InstantOverride.objects.all().delete()
    for pe in InstantProfileEntry.objects.filter(active=True):
        InstantOverride.objects.create(profile=pe.profile, control=pe.control, target_temp=pe.target_temp)
        pe.active = False
        pe.save()

class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0011_instantprofileentry_active'),
    ]

    operations = [
            migrations.RunPython(migrate_fwd, migrate_rev),
    ]
