# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0012_auto_20170506_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantoverride',
            name='control',
        ),
        migrations.RemoveField(
            model_name='instantoverride',
            name='profile',
        ),
        migrations.DeleteModel(
            name='InstantOverride',
        ),
    ]
