# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0013_auto_20170506_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
