# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-27 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


def fill_control_profile_holes_w_daytype(control, daytype, Profile):
    last_end = None

    for e in control.profile_set.filter(daytype=daytype).order_by('start'):
        if last_end is not None and last_end < e.start:
            control.profile_set.create(daytype=daytype, start=last_end, end=e.start, target_temp=None)

        last_end = e.end

    if last_end is not None and last_end != datetime.time():
        control.profile_set.create(daytype=daytype, start=last_end, end=datetime.time(), target_temp=None)


def fill_profile_holes(apps, schema_editor):
    Control = apps.get_model('heatcontrol', 'Control')
    Profile = apps.get_model('heatcontrol', 'Profile')
    daytypes = apps.get_model('heatcontrol', 'DayType').objects.all()

    for control in Control.objects.all():
        for daytype in daytypes:
            fill_control_profile_holes_w_daytype(control, daytype, Profile)


def remove_profile_holes(apps, schema_editor):
    Profile = apps.get_model('heatcontrol', 'Profile')

    Profile.objects.filter(target_temp=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0014_auto_20181227_0938'),
    ]

    operations = [
        migrations.RunPython(fill_profile_holes, remove_profile_holes),
    ]
