# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0015_heatcontrol_profile_add_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
