# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-27 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0017_heatcontrol_profile_end_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='end',
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set([('control', 'daytype', 'start')]),
        ),
    ]
