# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0018_auto_20181227_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoverride',
            name='end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledoverride',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
