# Generated by Django 2.2.6.dev20190924075833 on 2019-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0019_scheduledoverride_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='intabsmax',
            field=models.FloatField(default=100.0, null=True),
        ),
    ]
