# Generated by Django 5.2.2 on 2025-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatcontrol', '0021_auto_20191007_2004'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='heatcontrol_control_ab70c1_idx',
            old_fields=('control', 'daytype', 'start'),
        ),
        migrations.RenameIndex(
            model_name='scheduledoverride',
            new_name='heatcontrol_control_0db4ad_idx',
            old_fields=('control', 'end'),
        ),
        migrations.AlterUniqueTogether(
            name='instantprofileentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='instantprofileentry',
            constraint=models.UniqueConstraint(fields=('profile', 'control'), name='instantprofile_unique_profile_control'),
        ),
    ]
