# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: receiver/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='receiver/api.proto',
  package='receiver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12receiver/api.proto\x12\x08receiver\"#\n\x10\x43onfigureRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r\"$\n\x11\x43onfigureResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08\x32X\n\x08Receiver\x12L\n\x0f\x43onfigureSensor\x12\x1a.receiver.ConfigureRequest\x1a\x1b.receiver.ConfigureResponse\"\x00\x62\x06proto3')
)




_CONFIGUREREQUEST = _descriptor.Descriptor(
  name='ConfigureRequest',
  full_name='receiver.ConfigureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='receiver.ConfigureRequest.task_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_CONFIGURERESPONSE = _descriptor.Descriptor(
  name='ConfigureResponse',
  full_name='receiver.ConfigureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='started', full_name='receiver.ConfigureResponse.started', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['ConfigureRequest'] = _CONFIGUREREQUEST
DESCRIPTOR.message_types_by_name['ConfigureResponse'] = _CONFIGURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigureRequest = _reflection.GeneratedProtocolMessageType('ConfigureRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGUREREQUEST,
  __module__ = 'receiver.api_pb2'
  # @@protoc_insertion_point(class_scope:receiver.ConfigureRequest)
  ))
_sym_db.RegisterMessage(ConfigureRequest)

ConfigureResponse = _reflection.GeneratedProtocolMessageType('ConfigureResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURERESPONSE,
  __module__ = 'receiver.api_pb2'
  # @@protoc_insertion_point(class_scope:receiver.ConfigureResponse)
  ))
_sym_db.RegisterMessage(ConfigureResponse)



_RECEIVER = _descriptor.ServiceDescriptor(
  name='Receiver',
  full_name='receiver.Receiver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConfigureSensor',
    full_name='receiver.Receiver.ConfigureSensor',
    index=0,
    containing_service=None,
    input_type=_CONFIGUREREQUEST,
    output_type=_CONFIGURERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECEIVER)

DESCRIPTOR.services_by_name['Receiver'] = _RECEIVER

# @@protoc_insertion_point(module_scope)
