# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: receiver/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from configurator import api_pb2 as configurator_dot_api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='receiver/api.proto',
  package='receiver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12receiver/api.proto\x12\x08receiver\x1a\x16\x63onfigurator/api.proto\"!\n\x0eHandleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32H\n\x08Receiver\x12<\n\nHandleTask\x12\x12.configurator.Task\x1a\x18.receiver.HandleResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[configurator_dot_api__pb2.DESCRIPTOR,])




_HANDLERESPONSE = _descriptor.Descriptor(
  name='HandleResponse',
  full_name='receiver.HandleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='receiver.HandleResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['HandleResponse'] = _HANDLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandleResponse = _reflection.GeneratedProtocolMessageType('HandleResponse', (_message.Message,), dict(
  DESCRIPTOR = _HANDLERESPONSE,
  __module__ = 'receiver.api_pb2'
  # @@protoc_insertion_point(class_scope:receiver.HandleResponse)
  ))
_sym_db.RegisterMessage(HandleResponse)



_RECEIVER = _descriptor.ServiceDescriptor(
  name='Receiver',
  full_name='receiver.Receiver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleTask',
    full_name='receiver.Receiver.HandleTask',
    index=0,
    containing_service=None,
    input_type=configurator_dot_api__pb2._TASK,
    output_type=_HANDLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECEIVER)

DESCRIPTOR.services_by_name['Receiver'] = _RECEIVER

# @@protoc_insertion_point(module_scope)
