# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from configurator import api_pb2 as configurator_dot_api__pb2
from receiver import api_pb2 as receiver_dot_api__pb2


class ReceiverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HandleTask = channel.unary_unary(
        '/receiver.Receiver/HandleTask',
        request_serializer=configurator_dot_api__pb2.Task.SerializeToString,
        response_deserializer=receiver_dot_api__pb2.HandleResponse.FromString,
        )


class ReceiverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HandleTask(self, request, context):
    """Request to handle a sensor configuration task
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReceiverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HandleTask': grpc.unary_unary_rpc_method_handler(
          servicer.HandleTask,
          request_deserializer=configurator_dot_api__pb2.Task.FromString,
          response_serializer=receiver_dot_api__pb2.HandleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'receiver.Receiver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
