# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: receiver/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from configurator import api_pb2 as configurator_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12receiver/api.proto\x12\x08receiver\x1a\x16\x63onfigurator/api.proto\"!\n\x0eHandleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32H\n\x08Receiver\x12<\n\nHandleTask\x12\x12.configurator.Task\x1a\x18.receiver.HandleResponse\"\x00\x42\x31Z/github.com/rkojedzinszky/thermo-center/receiverb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'receiver.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/rkojedzinszky/thermo-center/receiver'
  _HANDLERESPONSE._serialized_start=56
  _HANDLERESPONSE._serialized_end=89
  _RECEIVER._serialized_start=91
  _RECEIVER._serialized_end=163
# @@protoc_insertion_point(module_scope)
