# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from configurator import api_pb2 as configurator_dot_api__pb2
from receiver import api_pb2 as receiver_dot_api__pb2


class ReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleTask = channel.unary_unary(
                '/receiver.Receiver/HandleTask',
                request_serializer=configurator_dot_api__pb2.Task.SerializeToString,
                response_deserializer=receiver_dot_api__pb2.HandleResponse.FromString,
                )


class ReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleTask(self, request, context):
        """Request to handle a sensor configuration task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleTask': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleTask,
                    request_deserializer=configurator_dot_api__pb2.Task.FromString,
                    response_serializer=receiver_dot_api__pb2.HandleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'receiver.Receiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Receiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/receiver.Receiver/HandleTask',
            configurator_dot_api__pb2.Task.SerializeToString,
            receiver_dot_api__pb2.HandleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
