# Generated by Django 2.2.3 on 2019-06-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_sensorresync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigureSensorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('first_discovery', models.DateTimeField(null=True)),
                ('last_discovery', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Sensor')),
            ],
        ),
    ]
