// Code generated by "stringer -type CommandStrobe cc1101.go"; DO NOT EDIT.

package cc1101

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SRES-48]
	_ = x[SFSTXON-49]
	_ = x[SXOFF-50]
	_ = x[SCAL-51]
	_ = x[SRX-52]
	_ = x[STX-53]
	_ = x[SIDLE-54]
	_ = x[SWOR-56]
	_ = x[SPWD-57]
	_ = x[SFRX-58]
	_ = x[SFTX-59]
	_ = x[SWORRST-60]
	_ = x[SNOP-61]
}

const (
	_CommandStrobe_name_0 = "SRESSFSTXONSXOFFSCALSRXSTXSIDLE"
	_CommandStrobe_name_1 = "SWORSPWDSFRXSFTXSWORRSTSNOP"
)

var (
	_CommandStrobe_index_0 = [...]uint8{0, 4, 11, 16, 20, 23, 26, 31}
	_CommandStrobe_index_1 = [...]uint8{0, 4, 8, 12, 16, 23, 27}
)

func (i CommandStrobe) String() string {
	switch {
	case 48 <= i && i <= 54:
		i -= 48
		return _CommandStrobe_name_0[_CommandStrobe_index_0[i]:_CommandStrobe_index_0[i+1]]
	case 56 <= i && i <= 61:
		i -= 56
		return _CommandStrobe_name_1[_CommandStrobe_index_1[i]:_CommandStrobe_index_1[i+1]]
	default:
		return "CommandStrobe(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
