// Code generated by "stringer -type StatusReg cc1101.go"; DO NOT EDIT.

package cc1101

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PARTNUM-48]
	_ = x[VERSION-49]
	_ = x[FREQEST-50]
	_ = x[LQI-51]
	_ = x[RSSI-52]
	_ = x[MARCSTATE-53]
	_ = x[WORTIME1-54]
	_ = x[WORTIME0-55]
	_ = x[PKTSTATUS-56]
	_ = x[VCO_VC_DAC-57]
	_ = x[TXBYTES-58]
	_ = x[RXBYTES-59]
	_ = x[RCCTRL1_STATUS-60]
	_ = x[RCCTRL0_STATUS-61]
}

const _StatusReg_name = "PARTNUMVERSIONFREQESTLQIRSSIMARCSTATEWORTIME1WORTIME0PKTSTATUSVCO_VC_DACTXBYTESRXBYTESRCCTRL1_STATUSRCCTRL0_STATUS"

var _StatusReg_index = [...]uint8{0, 7, 14, 21, 24, 28, 37, 45, 53, 62, 72, 79, 86, 100, 114}

func (i StatusReg) String() string {
	i -= 48
	if i >= StatusReg(len(_StatusReg_index)-1) {
		return "StatusReg(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _StatusReg_name[_StatusReg_index[i]:_StatusReg_index[i+1]]
}
