# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61ggregator/api.proto\x12\naggregator\"O\n\x0cSensorPacket\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0c\n\x04rssi\x18\x03 \x01(\x02\x12\x0b\n\x03lqi\x18\x04 \x01(\r\x12\x0b\n\x03raw\x18\x05 \x01(\x0c\"!\n\x0c\x46\x65\x65\x64Response\x12\x11\n\tprocessed\x18\x01 \x01(\x08\x32V\n\nAggregator\x12H\n\x10\x46\x65\x65\x64SensorPacket\x12\x18.aggregator.SensorPacket\x1a\x18.aggregator.FeedResponse\"\x00\x42\x33Z1github.com/rkojedzinszky/thermo-center/aggregatorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/rkojedzinszky/thermo-center/aggregator'
  _SENSORPACKET._serialized_start=36
  _SENSORPACKET._serialized_end=115
  _FEEDRESPONSE._serialized_start=117
  _FEEDRESPONSE._serialized_end=150
  _AGGREGATOR._serialized_start=152
  _AGGREGATOR._serialized_end=238
# @@protoc_insertion_point(module_scope)
