/* tslint:disable */
/* eslint-disable */
/**
 * Thermo Center API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfigureSensorTask,
  ConfigureSensorTaskW,
  Control,
  ControlW,
  DayType,
  DayTypeW,
  InstantProfile,
  InstantProfileW,
  ListControl200Response,
  ListDayType200Response,
  ListInstantProfile200Response,
  ListProfile200Response,
  ListScheduledOverride200Response,
  ListSensor200Response,
  ListSensorResync200Response,
  ListSession200Response,
  ListTHSensor200Response,
  PatchControlRequest,
  PatchDayTypeRequest,
  PatchInstantProfileRequest,
  PatchProfileRequest,
  PatchScheduledOverrideRequest,
  PatchSensorRequest,
  Profile,
  ProfileW,
  ScheduledOverride,
  ScheduledOverrideW,
  Sensor,
  SensorResync,
  SensorResyncW,
  SensorW,
  Session,
  SessionW,
  THSensor,
} from '../models/index';
import {
    ConfigureSensorTaskFromJSON,
    ConfigureSensorTaskToJSON,
    ConfigureSensorTaskWFromJSON,
    ConfigureSensorTaskWToJSON,
    ControlFromJSON,
    ControlToJSON,
    ControlWFromJSON,
    ControlWToJSON,
    DayTypeFromJSON,
    DayTypeToJSON,
    DayTypeWFromJSON,
    DayTypeWToJSON,
    InstantProfileFromJSON,
    InstantProfileToJSON,
    InstantProfileWFromJSON,
    InstantProfileWToJSON,
    ListControl200ResponseFromJSON,
    ListControl200ResponseToJSON,
    ListDayType200ResponseFromJSON,
    ListDayType200ResponseToJSON,
    ListInstantProfile200ResponseFromJSON,
    ListInstantProfile200ResponseToJSON,
    ListProfile200ResponseFromJSON,
    ListProfile200ResponseToJSON,
    ListScheduledOverride200ResponseFromJSON,
    ListScheduledOverride200ResponseToJSON,
    ListSensor200ResponseFromJSON,
    ListSensor200ResponseToJSON,
    ListSensorResync200ResponseFromJSON,
    ListSensorResync200ResponseToJSON,
    ListSession200ResponseFromJSON,
    ListSession200ResponseToJSON,
    ListTHSensor200ResponseFromJSON,
    ListTHSensor200ResponseToJSON,
    PatchControlRequestFromJSON,
    PatchControlRequestToJSON,
    PatchDayTypeRequestFromJSON,
    PatchDayTypeRequestToJSON,
    PatchInstantProfileRequestFromJSON,
    PatchInstantProfileRequestToJSON,
    PatchProfileRequestFromJSON,
    PatchProfileRequestToJSON,
    PatchScheduledOverrideRequestFromJSON,
    PatchScheduledOverrideRequestToJSON,
    PatchSensorRequestFromJSON,
    PatchSensorRequestToJSON,
    ProfileFromJSON,
    ProfileToJSON,
    ProfileWFromJSON,
    ProfileWToJSON,
    ScheduledOverrideFromJSON,
    ScheduledOverrideToJSON,
    ScheduledOverrideWFromJSON,
    ScheduledOverrideWToJSON,
    SensorFromJSON,
    SensorToJSON,
    SensorResyncFromJSON,
    SensorResyncToJSON,
    SensorResyncWFromJSON,
    SensorResyncWToJSON,
    SensorWFromJSON,
    SensorWToJSON,
    SessionFromJSON,
    SessionToJSON,
    SessionWFromJSON,
    SessionWToJSON,
    THSensorFromJSON,
    THSensorToJSON,
} from '../models/index';

export interface CreateConfigureSensorTaskRequest {
    configureSensorTaskW: ConfigureSensorTaskW;
}

export interface CreateControlRequest {
    controlW: ControlW;
}

export interface CreateDayTypeRequest {
    dayTypeW: DayTypeW;
}

export interface CreateInstantProfileRequest {
    instantProfileW: InstantProfileW;
}

export interface CreateProfileRequest {
    profileW: ProfileW;
}

export interface CreateScheduledOverrideRequest {
    scheduledOverrideW: ScheduledOverrideW;
}

export interface CreateSensorResyncRequest {
    sensorResyncW: SensorResyncW;
}

export interface CreateSessionRequest {
    sessionW: SessionW;
}

export interface DeleteControlRequest {
    id: number;
}

export interface DeleteDayTypeRequest {
    id: number;
}

export interface DeleteInstantProfileRequest {
    id: number;
}

export interface DeleteProfileRequest {
    id: number;
}

export interface DeleteScheduledOverrideRequest {
    id: number;
}

export interface DeleteSensorRequest {
    id: number;
}

export interface DeleteSessionRequest {
    id: number;
}

export interface GetConfigureSensorTaskRequest {
    id: number;
}

export interface GetControlRequest {
    id: number;
}

export interface GetDayTypeRequest {
    id: number;
}

export interface GetInstantProfileRequest {
    id: number;
}

export interface GetProfileRequest {
    id: number;
}

export interface GetScheduledOverrideRequest {
    id: number;
}

export interface GetSensorRequest {
    id: number;
}

export interface GetSensorResyncRequest {
    id: number;
}

export interface GetSessionRequest {
    id: number;
}

export interface GetTHSensorRequest {
    id: number;
}

export interface ListControlRequest {
    sensorId?: number;
}

export interface ListDayTypeRequest {
    name?: string;
}

export interface ListProfileRequest {
    control?: string;
    daytype?: string;
}

export interface ListScheduledOverrideRequest {
    control?: string;
}

export interface PatchControlOperationRequest {
    id: number;
    patchControlRequest: PatchControlRequest;
}

export interface PatchDayTypeOperationRequest {
    id: number;
    patchDayTypeRequest: PatchDayTypeRequest;
}

export interface PatchInstantProfileOperationRequest {
    id: number;
    patchInstantProfileRequest: PatchInstantProfileRequest;
}

export interface PatchProfileOperationRequest {
    id: number;
    patchProfileRequest: PatchProfileRequest;
}

export interface PatchScheduledOverrideOperationRequest {
    id: number;
    patchScheduledOverrideRequest: PatchScheduledOverrideRequest;
}

export interface PatchSensorOperationRequest {
    id: number;
    patchSensorRequest: PatchSensorRequest;
}

export interface PutControlRequest {
    id: number;
    controlW: ControlW;
}

export interface PutDayTypeRequest {
    id: number;
    dayTypeW: DayTypeW;
}

export interface PutInstantProfileRequest {
    id: number;
    instantProfileW: InstantProfileW;
}

export interface PutProfileRequest {
    id: number;
    profileW: ProfileW;
}

export interface PutScheduledOverrideRequest {
    id: number;
    scheduledOverrideW: ScheduledOverrideW;
}

export interface PutSensorRequest {
    id: number;
    sensorW: SensorW;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConfigureSensorTask without sending the request
     */
    async createConfigureSensorTaskRequestOpts(requestParameters: CreateConfigureSensorTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configureSensorTaskW'] == null) {
            throw new runtime.RequiredError(
                'configureSensorTaskW',
                'Required parameter "configureSensorTaskW" was null or undefined when calling createConfigureSensorTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/configuresensortask/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigureSensorTaskWToJSON(requestParameters['configureSensorTaskW']),
        };
    }

    /**
     * Create ConfigureSensorTask
     */
    async createConfigureSensorTaskRaw(requestParameters: CreateConfigureSensorTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigureSensorTask>> {
        const requestOptions = await this.createConfigureSensorTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigureSensorTaskFromJSON(jsonValue));
    }

    /**
     * Create ConfigureSensorTask
     */
    async createConfigureSensorTask(requestParameters: CreateConfigureSensorTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigureSensorTask> {
        const response = await this.createConfigureSensorTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createControl without sending the request
     */
    async createControlRequestOpts(requestParameters: CreateControlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['controlW'] == null) {
            throw new runtime.RequiredError(
                'controlW',
                'Required parameter "controlW" was null or undefined when calling createControl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/control/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ControlWToJSON(requestParameters['controlW']),
        };
    }

    /**
     * Create Control
     */
    async createControlRaw(requestParameters: CreateControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Control>> {
        const requestOptions = await this.createControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControlFromJSON(jsonValue));
    }

    /**
     * Create Control
     */
    async createControl(requestParameters: CreateControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Control> {
        const response = await this.createControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDayType without sending the request
     */
    async createDayTypeRequestOpts(requestParameters: CreateDayTypeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dayTypeW'] == null) {
            throw new runtime.RequiredError(
                'dayTypeW',
                'Required parameter "dayTypeW" was null or undefined when calling createDayType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/daytype/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DayTypeWToJSON(requestParameters['dayTypeW']),
        };
    }

    /**
     * Create DayType
     */
    async createDayTypeRaw(requestParameters: CreateDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DayType>> {
        const requestOptions = await this.createDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DayTypeFromJSON(jsonValue));
    }

    /**
     * Create DayType
     */
    async createDayType(requestParameters: CreateDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DayType> {
        const response = await this.createDayTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createInstantProfile without sending the request
     */
    async createInstantProfileRequestOpts(requestParameters: CreateInstantProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['instantProfileW'] == null) {
            throw new runtime.RequiredError(
                'instantProfileW',
                'Required parameter "instantProfileW" was null or undefined when calling createInstantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/instantprofile/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InstantProfileWToJSON(requestParameters['instantProfileW']),
        };
    }

    /**
     * Create InstantProfile
     */
    async createInstantProfileRaw(requestParameters: CreateInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createInstantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create InstantProfile
     */
    async createInstantProfile(requestParameters: CreateInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createInstantProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createProfile without sending the request
     */
    async createProfileRequestOpts(requestParameters: CreateProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['profileW'] == null) {
            throw new runtime.RequiredError(
                'profileW',
                'Required parameter "profileW" was null or undefined when calling createProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/profile/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileWToJSON(requestParameters['profileW']),
        };
    }

    /**
     * Create Profile
     */
    async createProfileRaw(requestParameters: CreateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const requestOptions = await this.createProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Create Profile
     */
    async createProfile(requestParameters: CreateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.createProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createScheduledOverride without sending the request
     */
    async createScheduledOverrideRequestOpts(requestParameters: CreateScheduledOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduledOverrideW'] == null) {
            throw new runtime.RequiredError(
                'scheduledOverrideW',
                'Required parameter "scheduledOverrideW" was null or undefined when calling createScheduledOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/scheduledoverride/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduledOverrideWToJSON(requestParameters['scheduledOverrideW']),
        };
    }

    /**
     * Create ScheduledOverride
     */
    async createScheduledOverrideRaw(requestParameters: CreateScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOverride>> {
        const requestOptions = await this.createScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOverrideFromJSON(jsonValue));
    }

    /**
     * Create ScheduledOverride
     */
    async createScheduledOverride(requestParameters: CreateScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOverride> {
        const response = await this.createScheduledOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSensorResync without sending the request
     */
    async createSensorResyncRequestOpts(requestParameters: CreateSensorResyncRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sensorResyncW'] == null) {
            throw new runtime.RequiredError(
                'sensorResyncW',
                'Required parameter "sensorResyncW" was null or undefined when calling createSensorResync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sensorresync/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SensorResyncWToJSON(requestParameters['sensorResyncW']),
        };
    }

    /**
     * Create SensorResync
     */
    async createSensorResyncRaw(requestParameters: CreateSensorResyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResync>> {
        const requestOptions = await this.createSensorResyncRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResyncFromJSON(jsonValue));
    }

    /**
     * Create SensorResync
     */
    async createSensorResync(requestParameters: CreateSensorResyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResync> {
        const response = await this.createSensorResyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSession without sending the request
     */
    async createSessionRequestOpts(requestParameters: CreateSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionW'] == null) {
            throw new runtime.RequiredError(
                'sessionW',
                'Required parameter "sessionW" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/session/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionWToJSON(requestParameters['sessionW']),
        };
    }

    /**
     * Create Session
     */
    async createSessionRaw(requestParameters: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        const requestOptions = await this.createSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Create Session
     */
    async createSession(requestParameters: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteControl without sending the request
     */
    async deleteControlRequestOpts(requestParameters: DeleteControlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteControl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/control/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single Control by primary key
     */
    async deleteControlRaw(requestParameters: DeleteControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single Control by primary key
     */
    async deleteControl(requestParameters: DeleteControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteControlRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteDayType without sending the request
     */
    async deleteDayTypeRequestOpts(requestParameters: DeleteDayTypeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDayType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/daytype/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single DayType by primary key
     */
    async deleteDayTypeRaw(requestParameters: DeleteDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single DayType by primary key
     */
    async deleteDayType(requestParameters: DeleteDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDayTypeRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteInstantProfile without sending the request
     */
    async deleteInstantProfileRequestOpts(requestParameters: DeleteInstantProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteInstantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/instantprofile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single InstantProfile by primary key
     */
    async deleteInstantProfileRaw(requestParameters: DeleteInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteInstantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single InstantProfile by primary key
     */
    async deleteInstantProfile(requestParameters: DeleteInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteInstantProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteProfile without sending the request
     */
    async deleteProfileRequestOpts(requestParameters: DeleteProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/profile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single Profile by primary key
     */
    async deleteProfileRaw(requestParameters: DeleteProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single Profile by primary key
     */
    async deleteProfile(requestParameters: DeleteProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteScheduledOverride without sending the request
     */
    async deleteScheduledOverrideRequestOpts(requestParameters: DeleteScheduledOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteScheduledOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scheduledoverride/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single ScheduledOverride by primary key
     */
    async deleteScheduledOverrideRaw(requestParameters: DeleteScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single ScheduledOverride by primary key
     */
    async deleteScheduledOverride(requestParameters: DeleteScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteScheduledOverrideRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSensor without sending the request
     */
    async deleteSensorRequestOpts(requestParameters: DeleteSensorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sensor/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single Sensor by primary key
     */
    async deleteSensorRaw(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSensorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single Sensor by primary key
     */
    async deleteSensor(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSensorRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSession without sending the request
     */
    async deleteSessionRequestOpts(requestParameters: DeleteSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/session/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a single Session by primary key
     */
    async deleteSessionRaw(requestParameters: DeleteSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a single Session by primary key
     */
    async deleteSession(requestParameters: DeleteSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSessionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConfigureSensorTask without sending the request
     */
    async getConfigureSensorTaskRequestOpts(requestParameters: GetConfigureSensorTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConfigureSensorTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/configuresensortask/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single ConfigureSensorTask by primary key
     */
    async getConfigureSensorTaskRaw(requestParameters: GetConfigureSensorTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigureSensorTask>> {
        const requestOptions = await this.getConfigureSensorTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigureSensorTaskFromJSON(jsonValue));
    }

    /**
     * Get a single ConfigureSensorTask by primary key
     */
    async getConfigureSensorTask(requestParameters: GetConfigureSensorTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigureSensorTask> {
        const response = await this.getConfigureSensorTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getControl without sending the request
     */
    async getControlRequestOpts(requestParameters: GetControlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getControl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/control/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single Control by primary key
     */
    async getControlRaw(requestParameters: GetControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Control>> {
        const requestOptions = await this.getControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControlFromJSON(jsonValue));
    }

    /**
     * Get a single Control by primary key
     */
    async getControl(requestParameters: GetControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Control> {
        const response = await this.getControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDayType without sending the request
     */
    async getDayTypeRequestOpts(requestParameters: GetDayTypeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDayType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/daytype/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single DayType by primary key
     */
    async getDayTypeRaw(requestParameters: GetDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DayType>> {
        const requestOptions = await this.getDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DayTypeFromJSON(jsonValue));
    }

    /**
     * Get a single DayType by primary key
     */
    async getDayType(requestParameters: GetDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DayType> {
        const response = await this.getDayTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInstantProfile without sending the request
     */
    async getInstantProfileRequestOpts(requestParameters: GetInstantProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInstantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/instantprofile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single InstantProfile by primary key
     */
    async getInstantProfileRaw(requestParameters: GetInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstantProfile>> {
        const requestOptions = await this.getInstantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstantProfileFromJSON(jsonValue));
    }

    /**
     * Get a single InstantProfile by primary key
     */
    async getInstantProfile(requestParameters: GetInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstantProfile> {
        const response = await this.getInstantProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProfile without sending the request
     */
    async getProfileRequestOpts(requestParameters: GetProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/profile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single Profile by primary key
     */
    async getProfileRaw(requestParameters: GetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const requestOptions = await this.getProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Get a single Profile by primary key
     */
    async getProfile(requestParameters: GetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.getProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScheduledOverride without sending the request
     */
    async getScheduledOverrideRequestOpts(requestParameters: GetScheduledOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getScheduledOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scheduledoverride/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single ScheduledOverride by primary key
     */
    async getScheduledOverrideRaw(requestParameters: GetScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOverride>> {
        const requestOptions = await this.getScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOverrideFromJSON(jsonValue));
    }

    /**
     * Get a single ScheduledOverride by primary key
     */
    async getScheduledOverride(requestParameters: GetScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOverride> {
        const response = await this.getScheduledOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSensor without sending the request
     */
    async getSensorRequestOpts(requestParameters: GetSensorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sensor/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single Sensor by primary key
     */
    async getSensorRaw(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sensor>> {
        const requestOptions = await this.getSensorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorFromJSON(jsonValue));
    }

    /**
     * Get a single Sensor by primary key
     */
    async getSensor(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sensor> {
        const response = await this.getSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSensorResync without sending the request
     */
    async getSensorResyncRequestOpts(requestParameters: GetSensorResyncRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSensorResync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sensorresync/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single SensorResync by primary key
     */
    async getSensorResyncRaw(requestParameters: GetSensorResyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResync>> {
        const requestOptions = await this.getSensorResyncRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResyncFromJSON(jsonValue));
    }

    /**
     * Get a single SensorResync by primary key
     */
    async getSensorResync(requestParameters: GetSensorResyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResync> {
        const response = await this.getSensorResyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSession without sending the request
     */
    async getSessionRequestOpts(requestParameters: GetSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/session/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single Session by primary key
     */
    async getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        const requestOptions = await this.getSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Get a single Session by primary key
     */
    async getSession(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.getSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTHSensor without sending the request
     */
    async getTHSensorRequestOpts(requestParameters: GetTHSensorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTHSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/thsensor/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single THSensor by primary key
     */
    async getTHSensorRaw(requestParameters: GetTHSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<THSensor>> {
        const requestOptions = await this.getTHSensorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => THSensorFromJSON(jsonValue));
    }

    /**
     * Get a single THSensor by primary key
     */
    async getTHSensor(requestParameters: GetTHSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<THSensor> {
        const response = await this.getTHSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listControl without sending the request
     */
    async listControlRequestOpts(requestParameters: ListControlRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['sensorId'] != null) {
            queryParameters['sensor_id'] = requestParameters['sensorId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/control/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of Control with filtering
     */
    async listControlRaw(requestParameters: ListControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListControl200Response>> {
        const requestOptions = await this.listControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListControl200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of Control with filtering
     */
    async listControl(requestParameters: ListControlRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListControl200Response> {
        const response = await this.listControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDayType without sending the request
     */
    async listDayTypeRequestOpts(requestParameters: ListDayTypeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/daytype/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of DayType with filtering
     */
    async listDayTypeRaw(requestParameters: ListDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDayType200Response>> {
        const requestOptions = await this.listDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDayType200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of DayType with filtering
     */
    async listDayType(requestParameters: ListDayTypeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDayType200Response> {
        const response = await this.listDayTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInstantProfile without sending the request
     */
    async listInstantProfileRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/instantprofile/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of InstantProfile with filtering
     */
    async listInstantProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListInstantProfile200Response>> {
        const requestOptions = await this.listInstantProfileRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListInstantProfile200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of InstantProfile with filtering
     */
    async listInstantProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListInstantProfile200Response> {
        const response = await this.listInstantProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProfile without sending the request
     */
    async listProfileRequestOpts(requestParameters: ListProfileRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['control'] != null) {
            queryParameters['control'] = requestParameters['control'];
        }

        if (requestParameters['daytype'] != null) {
            queryParameters['daytype'] = requestParameters['daytype'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/profile/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of Profile with filtering
     */
    async listProfileRaw(requestParameters: ListProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProfile200Response>> {
        const requestOptions = await this.listProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProfile200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of Profile with filtering
     */
    async listProfile(requestParameters: ListProfileRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProfile200Response> {
        const response = await this.listProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listScheduledOverride without sending the request
     */
    async listScheduledOverrideRequestOpts(requestParameters: ListScheduledOverrideRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['control'] != null) {
            queryParameters['control'] = requestParameters['control'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scheduledoverride/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of ScheduledOverride with filtering
     */
    async listScheduledOverrideRaw(requestParameters: ListScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListScheduledOverride200Response>> {
        const requestOptions = await this.listScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListScheduledOverride200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of ScheduledOverride with filtering
     */
    async listScheduledOverride(requestParameters: ListScheduledOverrideRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListScheduledOverride200Response> {
        const response = await this.listScheduledOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSensor without sending the request
     */
    async listSensorRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sensor/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of Sensor with filtering
     */
    async listSensorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSensor200Response>> {
        const requestOptions = await this.listSensorRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSensor200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of Sensor with filtering
     */
    async listSensor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSensor200Response> {
        const response = await this.listSensorRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSensorResync without sending the request
     */
    async listSensorResyncRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sensorresync/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of SensorResync with filtering
     */
    async listSensorResyncRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSensorResync200Response>> {
        const requestOptions = await this.listSensorResyncRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSensorResync200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of SensorResync with filtering
     */
    async listSensorResync(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSensorResync200Response> {
        const response = await this.listSensorResyncRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSession without sending the request
     */
    async listSessionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/session/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of Session with filtering
     */
    async listSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSession200Response>> {
        const requestOptions = await this.listSessionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of Session with filtering
     */
    async listSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSession200Response> {
        const response = await this.listSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTHSensor without sending the request
     */
    async listTHSensorRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/thsensor/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of THSensor with filtering
     */
    async listTHSensorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTHSensor200Response>> {
        const requestOptions = await this.listTHSensorRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTHSensor200ResponseFromJSON(jsonValue));
    }

    /**
     * Get list of THSensor with filtering
     */
    async listTHSensor(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTHSensor200Response> {
        const response = await this.listTHSensorRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchControl without sending the request
     */
    async patchControlRequestOpts(requestParameters: PatchControlOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchControl().'
            );
        }

        if (requestParameters['patchControlRequest'] == null) {
            throw new runtime.RequiredError(
                'patchControlRequest',
                'Required parameter "patchControlRequest" was null or undefined when calling patchControl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/control/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchControlRequestToJSON(requestParameters['patchControlRequest']),
        };
    }

    /**
     * Patch a single Control by primary key
     */
    async patchControlRaw(requestParameters: PatchControlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Control>> {
        const requestOptions = await this.patchControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControlFromJSON(jsonValue));
    }

    /**
     * Patch a single Control by primary key
     */
    async patchControl(requestParameters: PatchControlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Control> {
        const response = await this.patchControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchDayType without sending the request
     */
    async patchDayTypeRequestOpts(requestParameters: PatchDayTypeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchDayType().'
            );
        }

        if (requestParameters['patchDayTypeRequest'] == null) {
            throw new runtime.RequiredError(
                'patchDayTypeRequest',
                'Required parameter "patchDayTypeRequest" was null or undefined when calling patchDayType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/daytype/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchDayTypeRequestToJSON(requestParameters['patchDayTypeRequest']),
        };
    }

    /**
     * Patch a single DayType by primary key
     */
    async patchDayTypeRaw(requestParameters: PatchDayTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DayType>> {
        const requestOptions = await this.patchDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DayTypeFromJSON(jsonValue));
    }

    /**
     * Patch a single DayType by primary key
     */
    async patchDayType(requestParameters: PatchDayTypeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DayType> {
        const response = await this.patchDayTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchInstantProfile without sending the request
     */
    async patchInstantProfileRequestOpts(requestParameters: PatchInstantProfileOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchInstantProfile().'
            );
        }

        if (requestParameters['patchInstantProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'patchInstantProfileRequest',
                'Required parameter "patchInstantProfileRequest" was null or undefined when calling patchInstantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/instantprofile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchInstantProfileRequestToJSON(requestParameters['patchInstantProfileRequest']),
        };
    }

    /**
     * Patch a single InstantProfile by primary key
     */
    async patchInstantProfileRaw(requestParameters: PatchInstantProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.patchInstantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Patch a single InstantProfile by primary key
     */
    async patchInstantProfile(requestParameters: PatchInstantProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchInstantProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for patchProfile without sending the request
     */
    async patchProfileRequestOpts(requestParameters: PatchProfileOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchProfile().'
            );
        }

        if (requestParameters['patchProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'patchProfileRequest',
                'Required parameter "patchProfileRequest" was null or undefined when calling patchProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/profile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchProfileRequestToJSON(requestParameters['patchProfileRequest']),
        };
    }

    /**
     * Patch a single Profile by primary key
     */
    async patchProfileRaw(requestParameters: PatchProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const requestOptions = await this.patchProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Patch a single Profile by primary key
     */
    async patchProfile(requestParameters: PatchProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.patchProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchScheduledOverride without sending the request
     */
    async patchScheduledOverrideRequestOpts(requestParameters: PatchScheduledOverrideOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchScheduledOverride().'
            );
        }

        if (requestParameters['patchScheduledOverrideRequest'] == null) {
            throw new runtime.RequiredError(
                'patchScheduledOverrideRequest',
                'Required parameter "patchScheduledOverrideRequest" was null or undefined when calling patchScheduledOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/scheduledoverride/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchScheduledOverrideRequestToJSON(requestParameters['patchScheduledOverrideRequest']),
        };
    }

    /**
     * Patch a single ScheduledOverride by primary key
     */
    async patchScheduledOverrideRaw(requestParameters: PatchScheduledOverrideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOverride>> {
        const requestOptions = await this.patchScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOverrideFromJSON(jsonValue));
    }

    /**
     * Patch a single ScheduledOverride by primary key
     */
    async patchScheduledOverride(requestParameters: PatchScheduledOverrideOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOverride> {
        const response = await this.patchScheduledOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchSensor without sending the request
     */
    async patchSensorRequestOpts(requestParameters: PatchSensorOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchSensor().'
            );
        }

        if (requestParameters['patchSensorRequest'] == null) {
            throw new runtime.RequiredError(
                'patchSensorRequest',
                'Required parameter "patchSensorRequest" was null or undefined when calling patchSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sensor/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchSensorRequestToJSON(requestParameters['patchSensorRequest']),
        };
    }

    /**
     * Patch a single Sensor by primary key
     */
    async patchSensorRaw(requestParameters: PatchSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sensor>> {
        const requestOptions = await this.patchSensorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorFromJSON(jsonValue));
    }

    /**
     * Patch a single Sensor by primary key
     */
    async patchSensor(requestParameters: PatchSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sensor> {
        const response = await this.patchSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putControl without sending the request
     */
    async putControlRequestOpts(requestParameters: PutControlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putControl().'
            );
        }

        if (requestParameters['controlW'] == null) {
            throw new runtime.RequiredError(
                'controlW',
                'Required parameter "controlW" was null or undefined when calling putControl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/control/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ControlWToJSON(requestParameters['controlW']),
        };
    }

    /**
     * Overwrite a single Control by primary key
     */
    async putControlRaw(requestParameters: PutControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Control>> {
        const requestOptions = await this.putControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ControlFromJSON(jsonValue));
    }

    /**
     * Overwrite a single Control by primary key
     */
    async putControl(requestParameters: PutControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Control> {
        const response = await this.putControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putDayType without sending the request
     */
    async putDayTypeRequestOpts(requestParameters: PutDayTypeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putDayType().'
            );
        }

        if (requestParameters['dayTypeW'] == null) {
            throw new runtime.RequiredError(
                'dayTypeW',
                'Required parameter "dayTypeW" was null or undefined when calling putDayType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/daytype/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DayTypeWToJSON(requestParameters['dayTypeW']),
        };
    }

    /**
     * Overwrite a single DayType by primary key
     */
    async putDayTypeRaw(requestParameters: PutDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DayType>> {
        const requestOptions = await this.putDayTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DayTypeFromJSON(jsonValue));
    }

    /**
     * Overwrite a single DayType by primary key
     */
    async putDayType(requestParameters: PutDayTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DayType> {
        const response = await this.putDayTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putInstantProfile without sending the request
     */
    async putInstantProfileRequestOpts(requestParameters: PutInstantProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putInstantProfile().'
            );
        }

        if (requestParameters['instantProfileW'] == null) {
            throw new runtime.RequiredError(
                'instantProfileW',
                'Required parameter "instantProfileW" was null or undefined when calling putInstantProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/instantprofile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InstantProfileWToJSON(requestParameters['instantProfileW']),
        };
    }

    /**
     * Overwrite a single InstantProfile by primary key
     */
    async putInstantProfileRaw(requestParameters: PutInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putInstantProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Overwrite a single InstantProfile by primary key
     */
    async putInstantProfile(requestParameters: PutInstantProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putInstantProfileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for putProfile without sending the request
     */
    async putProfileRequestOpts(requestParameters: PutProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putProfile().'
            );
        }

        if (requestParameters['profileW'] == null) {
            throw new runtime.RequiredError(
                'profileW',
                'Required parameter "profileW" was null or undefined when calling putProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/profile/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileWToJSON(requestParameters['profileW']),
        };
    }

    /**
     * Overwrite a single Profile by primary key
     */
    async putProfileRaw(requestParameters: PutProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const requestOptions = await this.putProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Overwrite a single Profile by primary key
     */
    async putProfile(requestParameters: PutProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.putProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putScheduledOverride without sending the request
     */
    async putScheduledOverrideRequestOpts(requestParameters: PutScheduledOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putScheduledOverride().'
            );
        }

        if (requestParameters['scheduledOverrideW'] == null) {
            throw new runtime.RequiredError(
                'scheduledOverrideW',
                'Required parameter "scheduledOverrideW" was null or undefined when calling putScheduledOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/scheduledoverride/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduledOverrideWToJSON(requestParameters['scheduledOverrideW']),
        };
    }

    /**
     * Overwrite a single ScheduledOverride by primary key
     */
    async putScheduledOverrideRaw(requestParameters: PutScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOverride>> {
        const requestOptions = await this.putScheduledOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOverrideFromJSON(jsonValue));
    }

    /**
     * Overwrite a single ScheduledOverride by primary key
     */
    async putScheduledOverride(requestParameters: PutScheduledOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOverride> {
        const response = await this.putScheduledOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putSensor without sending the request
     */
    async putSensorRequestOpts(requestParameters: PutSensorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putSensor().'
            );
        }

        if (requestParameters['sensorW'] == null) {
            throw new runtime.RequiredError(
                'sensorW',
                'Required parameter "sensorW" was null or undefined when calling putSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sensor/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SensorWToJSON(requestParameters['sensorW']),
        };
    }

    /**
     * Overwrite a single Sensor by primary key
     */
    async putSensorRaw(requestParameters: PutSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sensor>> {
        const requestOptions = await this.putSensorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorFromJSON(jsonValue));
    }

    /**
     * Overwrite a single Sensor by primary key
     */
    async putSensor(requestParameters: PutSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sensor> {
        const response = await this.putSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
