# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurator/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configurator/api.proto',
  package='configurator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63onfigurator/api.proto\x12\x0c\x63onfigurator\"\"\n\x0fRadioCfgRequest\x12\x0f\n\x07\x63luster\x18\x01 \x01(\r\"J\n\x10RadioCfgResponse\x12\x0f\n\x07network\x18\x01 \x01(\r\x12\x14\n\x0cradio_config\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x65s_key\x18\x03 \x01(\x0c\x32^\n\x0c\x43onfigurator\x12N\n\x0bGetRadioCfg\x12\x1d.configurator.RadioCfgRequest\x1a\x1e.configurator.RadioCfgResponse\"\x00\x62\x06proto3')
)




_RADIOCFGREQUEST = _descriptor.Descriptor(
  name='RadioCfgRequest',
  full_name='configurator.RadioCfgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='configurator.RadioCfgRequest.cluster', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=74,
)


_RADIOCFGRESPONSE = _descriptor.Descriptor(
  name='RadioCfgResponse',
  full_name='configurator.RadioCfgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='configurator.RadioCfgResponse.network', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radio_config', full_name='configurator.RadioCfgResponse.radio_config', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aes_key', full_name='configurator.RadioCfgResponse.aes_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['RadioCfgRequest'] = _RADIOCFGREQUEST
DESCRIPTOR.message_types_by_name['RadioCfgResponse'] = _RADIOCFGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadioCfgRequest = _reflection.GeneratedProtocolMessageType('RadioCfgRequest', (_message.Message,), dict(
  DESCRIPTOR = _RADIOCFGREQUEST,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.RadioCfgRequest)
  ))
_sym_db.RegisterMessage(RadioCfgRequest)

RadioCfgResponse = _reflection.GeneratedProtocolMessageType('RadioCfgResponse', (_message.Message,), dict(
  DESCRIPTOR = _RADIOCFGRESPONSE,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.RadioCfgResponse)
  ))
_sym_db.RegisterMessage(RadioCfgResponse)



_CONFIGURATOR = _descriptor.ServiceDescriptor(
  name='Configurator',
  full_name='configurator.Configurator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=152,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRadioCfg',
    full_name='configurator.Configurator.GetRadioCfg',
    index=0,
    containing_service=None,
    input_type=_RADIOCFGREQUEST,
    output_type=_RADIOCFGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATOR)

DESCRIPTOR.services_by_name['Configurator'] = _CONFIGURATOR

# @@protoc_insertion_point(module_scope)
