# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurator/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configurator/api.proto',
  package='configurator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63onfigurator/api.proto\x12\x0c\x63onfigurator\"\"\n\x0fRadioCfgRequest\x12\x0f\n\x07\x63luster\x18\x01 \x01(\r\"J\n\x10RadioCfgResponse\x12\x0f\n\x07network\x18\x01 \x01(\r\x12\x14\n\x0cradio_config\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x65s_key\x18\x03 \x01(\x0c\"\x17\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\r\"a\n\x0bTaskDetails\x12\x0f\n\x07task_id\x18\x01 \x01(\r\x12\x11\n\tsensor_id\x18\x02 \x01(\r\x12.\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1e.configurator.RadioCfgResponse\"%\n\x12TaskUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x13TaskFinishedRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc6\x02\n\x0c\x43onfigurator\x12N\n\x0bGetRadioCfg\x12\x1d.configurator.RadioCfgRequest\x1a\x1e.configurator.RadioCfgResponse\"\x00\x12>\n\x0bTaskAcquire\x12\x12.configurator.Task\x1a\x19.configurator.TaskDetails\"\x00\x12O\n\x15TaskDiscoveryReceived\x12\x12.configurator.Task\x1a .configurator.TaskUpdateResponse\"\x00\x12U\n\x0cTaskFinished\x12!.configurator.TaskFinishedRequest\x1a .configurator.TaskUpdateResponse\"\x00\x62\x06proto3')
)




_RADIOCFGREQUEST = _descriptor.Descriptor(
  name='RadioCfgRequest',
  full_name='configurator.RadioCfgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='configurator.RadioCfgRequest.cluster', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=74,
)


_RADIOCFGRESPONSE = _descriptor.Descriptor(
  name='RadioCfgResponse',
  full_name='configurator.RadioCfgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='configurator.RadioCfgResponse.network', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radio_config', full_name='configurator.RadioCfgResponse.radio_config', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aes_key', full_name='configurator.RadioCfgResponse.aes_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=150,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='configurator.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='configurator.Task.task_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=175,
)


_TASKDETAILS = _descriptor.Descriptor(
  name='TaskDetails',
  full_name='configurator.TaskDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='configurator.TaskDetails.task_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='configurator.TaskDetails.sensor_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='configurator.TaskDetails.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=274,
)


_TASKUPDATERESPONSE = _descriptor.Descriptor(
  name='TaskUpdateResponse',
  full_name='configurator.TaskUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='configurator.TaskUpdateResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=313,
)


_TASKFINISHEDREQUEST = _descriptor.Descriptor(
  name='TaskFinishedRequest',
  full_name='configurator.TaskFinishedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='configurator.TaskFinishedRequest.task_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='configurator.TaskFinishedRequest.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=368,
)

_TASKDETAILS.fields_by_name['config'].message_type = _RADIOCFGRESPONSE
DESCRIPTOR.message_types_by_name['RadioCfgRequest'] = _RADIOCFGREQUEST
DESCRIPTOR.message_types_by_name['RadioCfgResponse'] = _RADIOCFGRESPONSE
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TaskDetails'] = _TASKDETAILS
DESCRIPTOR.message_types_by_name['TaskUpdateResponse'] = _TASKUPDATERESPONSE
DESCRIPTOR.message_types_by_name['TaskFinishedRequest'] = _TASKFINISHEDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadioCfgRequest = _reflection.GeneratedProtocolMessageType('RadioCfgRequest', (_message.Message,), dict(
  DESCRIPTOR = _RADIOCFGREQUEST,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.RadioCfgRequest)
  ))
_sym_db.RegisterMessage(RadioCfgRequest)

RadioCfgResponse = _reflection.GeneratedProtocolMessageType('RadioCfgResponse', (_message.Message,), dict(
  DESCRIPTOR = _RADIOCFGRESPONSE,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.RadioCfgResponse)
  ))
_sym_db.RegisterMessage(RadioCfgResponse)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.Task)
  ))
_sym_db.RegisterMessage(Task)

TaskDetails = _reflection.GeneratedProtocolMessageType('TaskDetails', (_message.Message,), dict(
  DESCRIPTOR = _TASKDETAILS,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.TaskDetails)
  ))
_sym_db.RegisterMessage(TaskDetails)

TaskUpdateResponse = _reflection.GeneratedProtocolMessageType('TaskUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKUPDATERESPONSE,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.TaskUpdateResponse)
  ))
_sym_db.RegisterMessage(TaskUpdateResponse)

TaskFinishedRequest = _reflection.GeneratedProtocolMessageType('TaskFinishedRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKFINISHEDREQUEST,
  __module__ = 'configurator.api_pb2'
  # @@protoc_insertion_point(class_scope:configurator.TaskFinishedRequest)
  ))
_sym_db.RegisterMessage(TaskFinishedRequest)



_CONFIGURATOR = _descriptor.ServiceDescriptor(
  name='Configurator',
  full_name='configurator.Configurator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=371,
  serialized_end=697,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRadioCfg',
    full_name='configurator.Configurator.GetRadioCfg',
    index=0,
    containing_service=None,
    input_type=_RADIOCFGREQUEST,
    output_type=_RADIOCFGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TaskAcquire',
    full_name='configurator.Configurator.TaskAcquire',
    index=1,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKDETAILS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TaskDiscoveryReceived',
    full_name='configurator.Configurator.TaskDiscoveryReceived',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKUPDATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TaskFinished',
    full_name='configurator.Configurator.TaskFinished',
    index=3,
    containing_service=None,
    input_type=_TASKFINISHEDREQUEST,
    output_type=_TASKUPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATOR)

DESCRIPTOR.services_by_name['Configurator'] = _CONFIGURATOR

# @@protoc_insertion_point(module_scope)
