# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurator/api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63onfigurator/api.proto\x12\x0c\x63onfigurator\"\"\n\x0fRadioCfgRequest\x12\x0f\n\x07\x63luster\x18\x01 \x01(\r\"J\n\x10RadioCfgResponse\x12\x0f\n\x07network\x18\x01 \x01(\r\x12\x14\n\x0cradio_config\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x65s_key\x18\x03 \x01(\x0c\"\x17\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\r\"a\n\x0bTaskDetails\x12\x0f\n\x07task_id\x18\x01 \x01(\r\x12\x11\n\tsensor_id\x18\x02 \x01(\r\x12.\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1e.configurator.RadioCfgResponse\"%\n\x12TaskUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x13TaskFinishedRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc6\x02\n\x0c\x43onfigurator\x12N\n\x0bGetRadioCfg\x12\x1d.configurator.RadioCfgRequest\x1a\x1e.configurator.RadioCfgResponse\"\x00\x12>\n\x0bTaskAcquire\x12\x12.configurator.Task\x1a\x19.configurator.TaskDetails\"\x00\x12O\n\x15TaskDiscoveryReceived\x12\x12.configurator.Task\x1a .configurator.TaskUpdateResponse\"\x00\x12U\n\x0cTaskFinished\x12!.configurator.TaskFinishedRequest\x1a .configurator.TaskUpdateResponse\"\x00\x42\x35Z3github.com/rkojedzinszky/thermo-center/configuratorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configurator.api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/rkojedzinszky/thermo-center/configurator'
  _RADIOCFGREQUEST._serialized_start=40
  _RADIOCFGREQUEST._serialized_end=74
  _RADIOCFGRESPONSE._serialized_start=76
  _RADIOCFGRESPONSE._serialized_end=150
  _TASK._serialized_start=152
  _TASK._serialized_end=175
  _TASKDETAILS._serialized_start=177
  _TASKDETAILS._serialized_end=274
  _TASKUPDATERESPONSE._serialized_start=276
  _TASKUPDATERESPONSE._serialized_end=313
  _TASKFINISHEDREQUEST._serialized_start=315
  _TASKFINISHEDREQUEST._serialized_end=368
  _CONFIGURATOR._serialized_start=371
  _CONFIGURATOR._serialized_end=697
# @@protoc_insertion_point(module_scope)
