// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: configurator/api.proto

package configurator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfiguratorClient is the client API for Configurator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfiguratorClient interface {
	// Return radio configuration for receiver
	GetRadioCfg(ctx context.Context, in *RadioCfgRequest, opts ...grpc.CallOption) (*RadioCfgResponse, error)
	// Sensor configuration task: Acquire
	TaskAcquire(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskDetails, error)
	// Sensor configuration task: Discovery received
	TaskDiscoveryReceived(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskUpdateResponse, error)
	// Sensor configuration task: finished
	TaskFinished(ctx context.Context, in *TaskFinishedRequest, opts ...grpc.CallOption) (*TaskUpdateResponse, error)
}

type configuratorClient struct {
	cc grpc.ClientConnInterface
}

func NewConfiguratorClient(cc grpc.ClientConnInterface) ConfiguratorClient {
	return &configuratorClient{cc}
}

func (c *configuratorClient) GetRadioCfg(ctx context.Context, in *RadioCfgRequest, opts ...grpc.CallOption) (*RadioCfgResponse, error) {
	out := new(RadioCfgResponse)
	err := c.cc.Invoke(ctx, "/configurator.Configurator/GetRadioCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configuratorClient) TaskAcquire(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/configurator.Configurator/TaskAcquire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configuratorClient) TaskDiscoveryReceived(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskUpdateResponse, error) {
	out := new(TaskUpdateResponse)
	err := c.cc.Invoke(ctx, "/configurator.Configurator/TaskDiscoveryReceived", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configuratorClient) TaskFinished(ctx context.Context, in *TaskFinishedRequest, opts ...grpc.CallOption) (*TaskUpdateResponse, error) {
	out := new(TaskUpdateResponse)
	err := c.cc.Invoke(ctx, "/configurator.Configurator/TaskFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfiguratorServer is the server API for Configurator service.
// All implementations must embed UnimplementedConfiguratorServer
// for forward compatibility
type ConfiguratorServer interface {
	// Return radio configuration for receiver
	GetRadioCfg(context.Context, *RadioCfgRequest) (*RadioCfgResponse, error)
	// Sensor configuration task: Acquire
	TaskAcquire(context.Context, *Task) (*TaskDetails, error)
	// Sensor configuration task: Discovery received
	TaskDiscoveryReceived(context.Context, *Task) (*TaskUpdateResponse, error)
	// Sensor configuration task: finished
	TaskFinished(context.Context, *TaskFinishedRequest) (*TaskUpdateResponse, error)
	mustEmbedUnimplementedConfiguratorServer()
}

// UnimplementedConfiguratorServer must be embedded to have forward compatible implementations.
type UnimplementedConfiguratorServer struct {
}

func (UnimplementedConfiguratorServer) GetRadioCfg(context.Context, *RadioCfgRequest) (*RadioCfgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadioCfg not implemented")
}
func (UnimplementedConfiguratorServer) TaskAcquire(context.Context, *Task) (*TaskDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskAcquire not implemented")
}
func (UnimplementedConfiguratorServer) TaskDiscoveryReceived(context.Context, *Task) (*TaskUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskDiscoveryReceived not implemented")
}
func (UnimplementedConfiguratorServer) TaskFinished(context.Context, *TaskFinishedRequest) (*TaskUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskFinished not implemented")
}
func (UnimplementedConfiguratorServer) mustEmbedUnimplementedConfiguratorServer() {}

// UnsafeConfiguratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfiguratorServer will
// result in compilation errors.
type UnsafeConfiguratorServer interface {
	mustEmbedUnimplementedConfiguratorServer()
}

func RegisterConfiguratorServer(s grpc.ServiceRegistrar, srv ConfiguratorServer) {
	s.RegisterService(&Configurator_ServiceDesc, srv)
}

func _Configurator_GetRadioCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RadioCfgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfiguratorServer).GetRadioCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configurator.Configurator/GetRadioCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfiguratorServer).GetRadioCfg(ctx, req.(*RadioCfgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurator_TaskAcquire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfiguratorServer).TaskAcquire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configurator.Configurator/TaskAcquire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfiguratorServer).TaskAcquire(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurator_TaskDiscoveryReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfiguratorServer).TaskDiscoveryReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configurator.Configurator/TaskDiscoveryReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfiguratorServer).TaskDiscoveryReceived(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configurator_TaskFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfiguratorServer).TaskFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configurator.Configurator/TaskFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfiguratorServer).TaskFinished(ctx, req.(*TaskFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Configurator_ServiceDesc is the grpc.ServiceDesc for Configurator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configurator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configurator.Configurator",
	HandlerType: (*ConfiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRadioCfg",
			Handler:    _Configurator_GetRadioCfg_Handler,
		},
		{
			MethodName: "TaskAcquire",
			Handler:    _Configurator_TaskAcquire_Handler,
		},
		{
			MethodName: "TaskDiscoveryReceived",
			Handler:    _Configurator_TaskDiscoveryReceived_Handler,
		},
		{
			MethodName: "TaskFinished",
			Handler:    _Configurator_TaskFinished_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configurator/api.proto",
}
